Repository ansible/vscode-ansible, pull requests merged in 2021-08, with the labels that each got.

#136 fix: switch publisher from zbr to redhat
  doc/development.md
  package.json
Labels: bug

#152 chore: rename master branch to main
  .github/workflows/ci.yaml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#154 chore: run commitlint on pr title
  .github/workflows/commitlint.yml
  .pre-commit-config.yaml
  commitlint.config.js
Labels: skip-changelog

#155 chore: upgrade npm lockfileVersion
  package-lock.json
Labels: skip-changelog

#157 fix: restore redhat branded extension icon
  icon.png
  images/logo.png
  package.json
Labels: bug

#159 feat: rename extension to redhat.ansible
  package-lock.json
  package.json
Labels: feature

#161 chore: updated urls after org move
  .github/ISSUE_TEMPLATE/config.yml
  package.json
Labels: bug

#137 feat: add context menus and commands for running playbooks
  package.json
  package.nls.json
  src/extension.ts
  src/features/runner.ts
Labels: feature

#165 chore: gitignore the pyenv config
  .gitignore
Labels: skip-changelog

#160 chore: add jenkins release pipeline
  Jenkinsfile
Labels: skip-changelog

#168 fix(issue forms): auto-label `new` issues on creation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog
