Repository ansible/vscode-ansible, pull requests merged in 2021-05, with the labels that each got.

#90 fix: reduce version of vscode required
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#99 fix: correct deps (2nd attempt)
  package-lock.json
  package.json
Labels: bug

#104 feat: auto add custom YAML tags
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  playbooks/dump_secrets.yml
  src/extension.ts
  src/features/config.ts
Labels: enhancement

#105 chore: add vsce package test
  .github/workflows/ci.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#106 fix: identify yaml playbooks
  CHANGELOG.md
  package.json
Labels: bug

#109 docs: added better instructions on how to use vault feature
  README.md
  doc/topics/vault_editing/README.md
  doc/topics/vault_editing/images/decrypt-full_file_vault.gif
  doc/topics/vault_editing/images/decrypt-inline_vault.gif
  doc/topics/vault_editing/images/encrypt-full_file_vault.gif
  doc/topics/vault_editing/images/encrypt-inline_vault.gif
Labels: documentation

#110 build: add vscode config files for debugging
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: enhancement
