Repository ansible/vscode-ansible, pull requests merged in 2021-11, with the labels that each got.

#288 Fix indentation when using inline vault encrypt
  src/features/vault.ts
Labels: bug

#291 Fix the line wrapping consistency in the changelog
  CHANGELOG.md
Labels: skip-changelog

#294 Refactor markdown linting
  .markdownlint.yaml
  .vscode/extensions.json
  README.md
  doc/development.md
  doc/topics/integrate_ansible-lint_in_venv/README.md
Labels: skip-changelog

#295 Prepare release 0.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#296 Activate extension when running ansible-vault
  package.json
Labels: bug

#298 Auto-select the only vault-id
  src/features/vault.ts
Labels: feature, minor

#300 changed default execution environment image
  package.json
Labels: feature

#309 Upgrade vscode-extension-tester
  package-lock.json
  package.json
Labels: skip-changelog

#308 Bump eslint to 8.2.0
  .pre-commit-config.yaml
  package-lock.json
  package.json
  src/features/runner.ts
Labels: skip-changelog

#310 Bump dependencies
  package-lock.json
  package.json
Labels: skip-changelog

#311 Add npm script to upgrade dependencies
  .ncurc.json
  package-lock.json
  package.json
Labels: skip-changelog, gate

#313 Add a guard for misleading selected lang in issues
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, skip-changelog, new

#317 Remove the need to configure ansible-playbook location
  README.md
  package.json
  src/features/runner.ts
Labels: bug

#318 Remove option to configure ansible-vault path
  README.md
  package.json
  package.nls.json
  src/features/vault.ts
Labels: bug, gate

#319 Document the need to have an opened workspace
  README.md
Labels: feature, gate

#321 Add job to run tests with latest ansible-language-server
  .github/workflows/ci.yaml
Labels: skip-changelog, gate

#334 Ensure npm link uses --save
  .github/workflows/ci.yaml
Labels: skip-changelog

#331 Make ansible/creator-ee:latest default execution environment
  .devcontainer/devcontainer.json
  package.json
Labels: bug, AAP

#333 Upgrade ansible-language-server to 0.3.0
  package-lock.json
  package.json
Labels: feature

#335 Prepare 0.7.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#338 Remove release pipeline
  .github/workflows/release.yaml
Labels: skip-changelog, gate

#342 Rename ui-test scrupt to test:ui
  .github/workflows/ci.yaml
  package.json
Labels: skip-changelog

#337 Fix inline encryption of multiline strings
  src/features/vault.ts
Labels: bug

#344 Upgrade ansible-language-server to 0.4.0
  .pre-commit-config.yaml
  README.md
  package-lock.json
  package.json
Labels: feature

#346 Prepare 0.7.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog
