Repository ansible/vscode-ansible, pull requests merged in 2021-03, with the labels that each got.

#29 feat: enable zuul config schema validation
  CHANGELOG.md
  package.json
Labels: enhancement

#30 feat: enable ansible-lint config file schema validation
  CHANGELOG.md
  package.json
Labels: enhancement

#31 feat: enable molecule scenario schema validation
  CHANGELOG.md
  package.json
Labels: enhancement

#27 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#32 chore: assure release workflow is triggered
  .github/workflows/release.yaml
Labels: skip-changelog

#33 chore: update release number to 0.2.0
  CHANGELOG.md
  package.json
Labels: skip-changelog

#34 fix: update badge to use PNG
  CHANGELOG.md
  package.json
Labels: bug

#37 feat: add common file associations
  CHANGELOG.md
  package.json
Labels: enhancement

#38 chore: update pre-commit configuration
  .commitlintrc.json
  .devcontainer/devcontainer.json
  .eslintrc.json
  .pre-commit-config.yaml
  package-lock.json
  package.json
  package.nls.json
  tsconfig.json
Labels: skip-changelog

#41 feat: use dedicated output channel
  src/extension.ts
Labels: enhancement

#43 feat: add schema for galaxy.yml files
  CHANGELOG.md
  package.json
Labels: enhancement

#46 Fix typo in README.md
  CHANGELOG.md
Labels: bug

#45 Add an explicit extension dependency on vscode-yaml
  package.json
Labels: bug

#53 chore: fix pre-commit eslint dependencies
  .pre-commit-config.yaml
Labels: bug

#52 Create LICENSE
  LICENSE
Labels: bug

#54 fix: advertise Microsoft Python extension as required
  package.json
Labels: bug
