Repository ansible/vscode-ansible, pull requests merged in 2021-09, with the labels that each got.

#169 fix: restore schema verification for some files
  package.json
Labels: bug

#187 chore: ensure synced package-lock.json
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#189 chore: treat eslint warnings as errors
  .pre-commit-config.yaml
Labels: skip-changelog

#190 fix: change version to 0.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#191 chore: prevent incorrect versions
  .pre-commit-config.yaml
Labels: skip-changelog

#192 fix: update dependencies
  package-lock.json
Labels: bug

#201 chore: fix pre-commit.ci failure
  .pre-commit-config.yaml
Labels: skip-changelog

#199 fix: update compile withserver script
  package.json
Labels: skip-changelog

#196 feat: update default setting value for using FQCN
  package.json
Labels: feature

#205 chore: avoid changing quotes on yaml files
  .prettierrc
  .prettierrc.yaml
Labels: skip-changelog

#204 chore: test extension installation in vscode
  .github/workflows/ci.yaml
  .gitignore
  package-lock.json
  package.json
Labels: skip-changelog

#170 feat: prompt to uninstall incompatible extensions
  CHANGELOG.md
  src/extension.ts
  src/extensionConflicts.ts
Labels: feature

#203 chore: include marketplace links in first paragraph
  README.md
Labels: skip-changelog
