Repository ansible/vscode-ansible, pull requests merged in 2021-04, with the labels that each got.

#61 docs: mention YAML tags configuration
  README.md
Labels: documentation

#62 feat: add logging information
  src/extension.ts
  src/features/validationProvider.ts
Labels: enhancement

#63 build: 0.3.1 release
  CHANGELOG.md
  package.json
Labels: documentation

#68 Use ansible-lint severity for VSCode diagnostics
  src/features/validationProvider.ts
Labels: enhancement

#67 docs: added instructions on how to integrate `ansible-lint` in venv w…
  README.md
  doc/topics/integrate_ansible-lint_in_venv/README.md
  doc/topics/integrate_ansible-lint_in_venv/images/vscode_remote_wsl1.png
  doc/topics/integrate_ansible-lint_in_venv/images/vscode_remote_wsl2.png
  doc/topics/integrate_ansible-lint_in_venv/linux.md
  doc/topics/integrate_ansible-lint_in_venv/mac.md
  doc/topics/integrate_ansible-lint_in_venv/windows.md
Labels: documentation

#70 Match found problems to source files
  package.json
  src/features/validationProvider.ts
Labels: bug

#71 build: release 0.3.2
  CHANGELOG.md
  package.json
Labels: skip-changelog

#72 build: run publish only on release
  .github/workflows/release.yaml
Labels: skip-changelog

#75 build: replace use of pre-commit.ci with github action
  .eslintrc.json
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  package.json
Labels: enhancement

#73 build: assure package lock file is updated
  .pre-commit-config.yaml
  package-lock.json
Labels: skip-changelog

#80 chore: assure commitlint runs
  .github/workflows/commitlint.yml
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
Labels: skip-changelog

#78 feat: add support for editing vaults
  .pass
  CHANGELOG.md
  README.md
  ansible.cfg
  package-lock.json
  package.json
  package.nls.json
  playbooks/dump_secrets.yml
  playbooks/vars/secrets.yml
  src/extension.ts
  src/features/utils/ansibleCfg.ts
  src/features/vault.ts
  src/test/suite/index.ts
  tsconfig.json
Labels: enhancement

#82 chore: release 0.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#86 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#87 chore: document schema selection
  README.md
Labels: documentation
