Repository ansible/vscode-ansible, pull requests merged in 2022-12, with the labels that each got.

#705 Update location of ansible schemas
  package.json
Labels: bug

#714 Update test settings.json to force use of docker
  test/testFixtures/settings.json
Labels: skip-changelog

#713 Use ubuntu-22.04
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  tools/test-setup.sh
Labels: skip-changelog

#720 Build script and deps updates
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  Taskfile.yml
  package.json
  tools/test-setup.sh
  yarn.lock
Labels: skip-changelog

#723 test-setup: improve test-setup
  .config/Containerfile
  .config/dictionary.txt
  Taskfile.yml
  tools/get-image-version
  tools/test-setup.sh
Labels: skip-changelog

#725 Replace vsce with @vscode/vsce
  Jenkinsfile
  Taskfile.yml
  package.json
  yarn.lock
Labels: skip-changelog

#726 Ensure we run GHA on devel/* branches
  .github/workflows/ci.yaml
Labels: skip-changelog

#727 Use same constraints as creator-ee
  .config/requirements.in
  .config/requirements.txt
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#729 More test-setup.sh
  .gitignore
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#732 Add Red Hat telemetry gathering
  .vscode/launch.json
  .vscode/settings.json
  README.md
  USAGE_DATA.md
  package.json
  src/definitions/constants.ts
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/runner.ts
  src/utils/registerCommands.ts
  src/utils/telemetryUtils.ts
  yarn.lock
Labels: feature

#733 Upgrade ALS to 1.0.4
  package.json
  src/features/ansibleMetaData.ts
  src/features/utils/formatAnsibleMetaData.ts
  yarn.lock
Labels: bug

#734 Refactor build scripts
  .github/release-drafter.yml
  Jenkinsfile
  Taskfile.yml
  tools/test-setup.sh
  webpack.config.js
Labels: skip-changelog

#735 Replace unmaintained xvfb action
  .github/workflows/ci.yaml
Labels: skip-changelog

#736 Fix release script
  tools/release.sh
Labels: skip-changelog

#738 Update deps
  .github/workflows/release.yml
  .pre-commit-config.yaml
  package.json
  yarn.lock
Labels: skip-changelog

#739 Update badges
  package.json
Labels: skip-changelog
