Repository ansible/vscode-ansible, pull requests merged in 2022-09, with the labels that each got.

#611 fix hyphenation README
  README.md
Labels: bug

#617 Add auto-detection of Ansible files based on their content
  README.md
  examples/vault-ids-example/play.yml
  examples/with_modelines.yml
  examples/without_modelines.yml
  src/extension.ts
  src/features/fileAssociation.ts
  src/features/utils/applyFileInspectionForKeywords.ts
  src/features/utils/applyModelines.ts
Labels: feature

#619 Update pre-commit hooks
  .pre-commit-config.yaml
  .prettierrc.yaml
Labels: skip-changelog

#622 Updated deps
  package.json
  yarn.lock
Labels: bug, skip-changelog

#627 Change extension status-bar icon
  src/extension.ts
Labels: bug

#626 bump vscode-languageclient from 7.x to 8.x
  package.json
  src/extension.ts
  src/extensionConflicts.ts
  yarn.lock
Labels: bug

#632 Update ALS to 0.10.3 (3 bugs)
  package.json
  yarn.lock
Labels: bug

#637 Switch to new location of Molecule JSON Schema
  package.json
Labels: bug

#635 Refactor extension.ts
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/runner.ts
  src/features/utils/applyFileInspectionForKeywords.ts
  src/features/utils/applyModelines.ts
Labels: bug

#639 chore: bump ALS to 0.10.3
  package.json
  yarn.lock
Labels: skip-changelog

#640 Simplify bug report
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: skip-changelog
