Repository ansible/vscode-ansible, pull requests merged in 2022-01, with the labels that each got.

#365 Add schema for ansible-navigator configuration
  package.json
Labels: feature

#371 Fix the check job in GHA workflows
  .github/workflows/ci.yaml
Labels: bug, skip-changelog

#366 Declare lextudio.restructuredtext ext as conflicting
  src/extensionConflicts.ts
Labels: bug

#374 chore: add dependabot config
  .github/dependabot.yml
Labels: skip-changelog

#381 chore: isolate extensions for test:ui
  package.json
Labels: skip-changelog

#343 Updated readme with install and activate instructions
  README.md
Labels: documentation, skip-changelog

#386 chore: use prettier with markdown
  .pre-commit-config.yaml
  .prettierrc.yaml
  CHANGELOG.md
  README.md
  doc/development.md
  doc/topics/integrate_ansible-lint_in_venv/README.md
  examples/REAME.md
Labels: bug, skip-changelog

#385 chore: ensure we have working ansible-lint on gha
  .github/workflows/ci.yaml
Labels: skip-changelog

#389 chore: improve vscode in-repo settings
  .pre-commit-config.yaml
  .vscode/settings.json
Labels: skip-changelog

#387 chore: use prettier with json
  .ncurc.json
  .pre-commit-config.yaml
  .prettierignore
  .vscode/extensions.json
  .vscode/launch.json
Labels: bug, skip-changelog

#382 e2e-test: add ansible diagnostic tests
  src/test/helper.ts
  src/test/testFixtures/diagnostics/ansible/1.yml
  src/test/testFixtures/diagnostics/ansible/2.yml
  src/test/testScripts/diagnostics/testDiagnosticsAnsibleLocal.test.ts
  src/test/testScripts/testExtensionLocal.test.ts
Labels: skip-changelog

#388 chore: enable yamllint
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .yamllint
Labels: bug, skip-changelog, quorum-required

#397 Move test files to standard location
  .mocharc.yml
  package.json
  test/helper.ts
  test/index.ts
  test/testFixtures/common/collections/ansible_collections/testorg/collection_1/galaxy.yml
  test/testFixtures/common/collections/ansible_collections/testorg/collection_1/plugins/lookup/lookup_1.py
  test/testFixtures/common/collections/ansible_collections/testorg/collection_1/plugins/modules/module_1.py
  test/testFixtures/diagnostics/ansible/1.yml
  test/testFixtures/diagnostics/ansible/2.yml
  test/testFixtures/hover/1.yml
  test/testFixtures/settings.json
  test/testRunner.ts
  test/testScripts/diagnostics/testDiagnosticsAnsibleLocal.test.ts
  test/testScripts/hover/testHoverLocal.test.ts
  test/testScripts/testExtensionLocal.test.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/extensionUITest.ts
  tsconfig.json
Labels: skip-changelog

#398 Recommend mocha-test-adapter vscode extension to contributors
  .vscode/extensions.json
Labels: skip-changelog

#399 Add retries for extension finding
  test/ui-test/extensionUITest.ts
Labels: skip-changelog

#396 e2e-test: add yaml diagnostic tests
  .pre-commit-config.yaml
  test/testFixtures/diagnostics/yaml/invalid_yaml.yml
  test/testScripts/diagnostics/testDiagnosticsYAMLLocal.test.ts
  test/testScripts/testExtensionLocal.test.ts
Labels: feature, skip-changelog

#404 Use dependabot only with production dependencies
  .github/dependabot.yml
Labels: skip-changelog

#409 Make test-setup script a standalone file
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: skip-changelog

#410 Use bashate with shells scripts
  .pre-commit-config.yaml
  tools/test-setup.sh
Labels: skip-changelog

#413 chore: make mocha output colorful on GHA
  .github/workflows/ci.yaml
Labels: skip-changelog
