Repository ansible/vscode-ansible, pull requests merged in 2022-03, with the labels that each got.

#432 Fix jsonValidation and yamlValidation extension point
  package.json
Labels: bug

#434 Update ansible-language-server version
  package-lock.json
  package.json
Labels: enhancement

#437 Restore webpack archive
  .vscodeignore
  package.json
Labels: bug

#438 Avoid complex string expansions
  src/features/runner.ts
  src/features/vault.ts
Labels: skip-changelog

#439 Update vsce version
  package-lock.json
  package.json
Labels: skip-changelog

#442 Fix testing of unreleased ansible-language-server (devel)
  .github/workflows/ci.yaml
Labels: skip-changelog

#443 Bump test dependencies
  package-lock.json
  package.json
Labels: skip-changelog

#440 Release 0.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#446 Ensure we run webpack within Jenkinsfile
  Jenkinsfile
Labels: skip-changelog

#444 Prepare fixtures for ansible-lint v6
  test/testFixtures/diagnostics/ansible/1.yml
  test/testFixtures/diagnostics/ansible/2.yml
Labels: skip-changelog

#452 Enable cspell
  .config/dictionary.txt
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Jenkinsfile
  cspell.config.yaml
  src/features/vault.ts
  test/testFixtures/diagnostics/yaml/invalid_yaml.yml
  test/testScripts/hover/testHoverLocal.test.ts
  webpack.config.js
Labels: skip-changelog

#454 Add language configuration files in vsix package
  .vscodeignore
Labels: bug

#455 Release 0.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#407 Reformat typescript using prettier
  .eslintrc.json
  .pre-commit-config.yaml
  .prettierrc.yaml
  commitlint.config.js
  src/extension.ts
  src/extensionConflicts.ts
  src/features/runner.ts
  src/features/utils/ansibleCfg.ts
  src/features/vault.ts
  test/helper.ts
  test/index.ts
  test/testRunner.ts
  test/testScripts/diagnostics/testDiagnosticsAnsibleLocal.test.ts
  test/testScripts/diagnostics/testDiagnosticsYAMLLocal.test.ts
  test/testScripts/hover/testHoverLocal.test.ts
  test/testScripts/testExtensionLocal.test.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/extensionUITest.ts
  webpack.config.js
Labels: skip-changelog

#462 Add vscode test launch configuration
  .vscode/launch.json
Labels: skip-changelog

#470 Remove Zuul schema definition from extension config
  package.json
Labels: bug
