Repository ansible/vscode-ansible, pull requests merged in 2022-08, with the labels that each got.

#577 Update test dependencies
  .config/dictionary.txt
  .pre-commit-config.yaml
  package.json
  yarn.lock
Labels: bug

#579 Do not open welcome page during testing
  test/testFixtures/settings.json
Labels: skip-changelog

#588 Fix macos build failure
  Taskfile.yml
Labels: skip-changelog

#589 Upgrade @ansible/ansible-language-server to 0.10.0
  package.json
  yarn.lock
Labels: bug, skip-changelog

#586 Add feature to show ansible meta data
  src/extension.ts
  src/formatAnsibleMetaData.ts
Labels: feature

#593 Allow jinja brace autocompletion
  ansible-language-configuration.json
Labels: feature, minor

#598 Remove preview label from extension
  package.json
Labels: skip-changelog

#600 Add feature to dynamically associate yaml files to `ansible` language
  .config/dictionary.txt
  examples/vault-ids-example/play.yml
  examples/with_double_ext.ansible.yml
  examples/with_modelines.yml
  package.json
  src/extension.ts
  src/features/fileAssociation.ts
  src/features/utils/applyModelines.ts
Labels: feature

#602 Update pre-commit hooks
  .pre-commit-config.yaml
  README.md
  package.json
Labels: skip-changelog

#603 Disable python debugger when running external commands
  package.json
  yarn.lock
Labels: bug

#605 Fix the display of double `Ansible` in status-bar text
  src/extension.ts
  src/features/utils/formatAnsibleMetaData.ts
Labels: bug

#608 Use new location of ansible-lint config JSON Schema
  package.json
Labels: bug
