Repository ansible/vscode-ansible, pull requests merged in 2022-04, with the labels that each got.

#473 Add verbose logging for ALS in test-e2e
  test/helper.ts
  test/testScripts/testExtensionLocal.test.ts
Labels: skip-changelog

#474 Bump pre-commit hooks
  .pre-commit-config.yaml
  package-lock.json
  package.json
Labels: skip-changelog

#476 Add vsce script in package.json
  package.json
Labels: skip-changelog

#475 Add tox config and update dev deps
  package-lock.json
  package.json
  tox.ini
Labels: skip-changelog

#478 Add all test commands to tox
  doc/development.md
  package.json
  tox.ini
Labels: skip-changelog

#480 Update URL of external resources
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  package.json
Labels: bug, AAP

#482 Enable testing with unreleased version of ALS (devel)
  .github/workflows/ci.yaml
Labels: skip-changelog

#483 Avoid telemetry popup from YAML extension
  .vscode/settings.json
  test/testFixtures/settings.json
Labels: skip-changelog

#459 Add e2e testcases for execution-environment
  .config/dictionary.txt
  .github/workflows/ci.yaml
  package.json
  test/helper.ts
  test/index.ts
  test/testFixtures/diagnostics/ansible/without_ee/1.yml
  test/testFixtures/diagnostics/ansible/without_ee/2.yml
  test/testFixtures/hover/with_ee/1.yml
  test/testFixtures/hover/without_ee/1.yml
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
  test/testScripts/diagnostics/testYamlWithoutEE.test.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
  test/testScripts/hover/testWithEE.test.ts
  test/testScripts/hover/testWithoutEE.test.ts
  test/testScripts/testExtensionLocal.test.ts
Labels: fug, enhancement
