Repository ansible/vscode-ansible, pull requests merged in 2022-11, with the labels that each got.

#673 Add event driven schema for autocompletion and diagnostics of EDA rules
  .config/dictionary.txt
  package.json
Labels: feature

#677 Enhance ansible metadata and Bump ALS version from 1.0.1 to to 1.0.2
  examples/playbooks/.ansible-lint
  examples/playbooks/play2.yml
  package.json
  src/features/ansibleMetaData.ts
  src/features/utils/formatAnsibleMetaData.ts
  yarn.lock
Labels: bug, enhancement

#685 Use shellcheck-py
  .pre-commit-config.yaml
Labels: skip-changelog

#683 Enables reuse of existing ansible terminals
  src/features/runner.ts
Labels: bug

#689 Reuse terminal setting
  README.md
  package.json
  src/features/runner.ts
  test/testFixtures/settings.json
Labels: enhancement

#691 Update search paths for ansible.cfg based on the documentation
  src/features/utils/ansibleCfg.ts
Labels: bug

#693 Fix broken pipe error in test-setup.sh
  tools/test-setup.sh
Labels: bug

#697 Update yarn
  .devcontainer/devcontainer.json
  .yarn/releases/yarn-3.2.1.cjs
  .yarn/releases/yarn-3.3.0.cjs
  .yarnrc.yml
  package.json
  test/testFixtures/settings.json
  tools/test-setup.sh
  yarn.lock
Labels: skip-changelog

#698 Update build and test dependencies
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  Taskfile.yml
  package.json
  yarn.lock
Labels: bug, skip-changelog

#700 Improve podman machine bootrapping
  tools/test-setup.sh
Labels: skip-changelog
