Repository ansible/vscode-ansible, pull requests merged in 2022-05, with the labels that each got.

#491 Prepare 0.9.0 changelog
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#493 Update release pipeline
  .config/dictionary.txt
  .gitignore
  Jenkinsfile
Labels: skip-changelog

#494 release/0.9.0
  Jenkinsfile
Labels: skip-changelog

#495 More jenkins fixes
  .config/dictionary.txt
  Jenkinsfile
Labels: skip-changelog

#496 More jenkins
  Jenkinsfile
Labels: skip-changelog

#497 Sorted warning from Jenkins
  Jenkinsfile
Labels: skip-changelog

#499 Add EE settings for volume mounts, container options and pull arguments
  .github/workflows/ci.yaml
  README.md
  package-lock.json
  package.json
  test/helper.ts
  test/testFixtures/settings.json
  test/testRunner.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
  test/testScripts/hover/testWithEE.test.ts
Labels: AAP, enhancement

#506 Upgrade ansible-language-server to 0.7.2
  package-lock.json
  package.json
Labels: bug

#507 Update test dependencies
  .ncurc.json
  package-lock.json
  package.json
Labels: skip-changelog
