Repository ansible/vscode-ansible, pull requests merged in 2023-07, with the labels that each got.

#945 Update runner.ts to correctly get the path of ansible
  src/features/runner.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#884 Add ability to select and set cursor on vars following `_var_` pattern
  src/features/lightspeed/inlineSuggestions.ts
  src/features/utils/lightspeed.ts
Labels: feature

#940 Fix ansibleContent feedback event trigger
  src/definitions/lightspeed.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
Labels: bug

#948 Update lightspeed task name regex match condition (#947)
  src/features/lightspeed/inlineSuggestions.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#943 Upgrade ALS v1.2.0
  package.json
  yarn.lock
Labels: skip-changelog

#949 Fix command runner
  examples/with_double_ext.ansible.yml
  src/features/utils/commandRunner.ts
Labels: bug

#950 Upgrade als to v1.2.1
  package.json
  yarn.lock
Labels: bug, enhancement
