Repository ansible/vscode-ansible, pull requests merged in 2023-01, with the labels that each got.

#743 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#742 Address vsix variable exception in Jenkinsfile
  Jenkinsfile
Labels: skip-changelog

#744 Switch from quay.io to ghcr.io
  .config/Containerfile
  package.json
  src/settings.ts
Labels: bug

#747 Add tsdoc to eslint
   tsdoc.json
  .config/dictionary.txt
  .eslintrc.json
  .pre-commit-config.yaml
  .vscode/settings.json
  Taskfile.yml
  package.json
  src/features/fileAssociation.ts
  src/features/runner.ts
  src/features/utils/applyModelines.ts
  src/features/utils/commandRunner.ts
  src/utils/registerCommands.ts
  src/utils/telemetryUtils.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/extensionUITest.ts
  webpack.config.ts
  yarn.lock
Labels: bug

#740 Clean deps
  .config/dictionary.txt
  .depcheckrc.yml
  Taskfile.yml
  package.json
  yarn.lock
Labels: skip-changelog

#749 Convert eslint config to yaml
  .eslintrc.json
  .eslintrc.yml
Labels: skip-changelog

#751 Upgrade telemetry to 0.5.4
  package.json
  yarn.lock
Labels: bug

#752 Treat webpack warnings as errors
  package.json
  webpack.config.ts
  yarn.lock
Labels: skip-changelog

#767 Add extra logging to macos podman machine start sequence
  tools/test-setup.sh
Labels: skip-changelog

#766 Add code changes for inline suggestion [part-1]
  .config/dictionary.txt
  package.json
  src/definitions/constants.ts
  src/definitions/wisdom.ts
  src/extension.ts
  src/features/utils/dateTime.ts
  src/features/utils/wisdom.ts
  src/features/wisdom/api.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  src/utils/keyInputUtils.ts
  src/utils/settings.ts
  test/ui-test/extensionUITest.ts
  yarn.lock
Labels: feature
