Repository ansible/vscode-ansible, pull requests merged in 2023-04, with the labels that each got.

#838 Update wisdom survey link
  src/definitions/constants.ts
Labels: enhancement

#839 Improve message handling for status code 204
  src/features/wisdom/api.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: bug

#841 Check for valid YAML for wisdom
  src/features/wisdom/inlineSuggestions.ts
  src/features/wisdom/utils/data.ts
Labels: enhancement

#842 Update console logs for wisdom service
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: skip-changelog

#843 Fix wisdom basePath empty/leading and trailing space issue
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
  src/features/wisdom/utils/webUtils.ts
Labels: bug

#849 Fix to provide inline suggestions on click
  src/extension.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: bug

#850 Update depedencies
  .pre-commit-config.yaml
  yarn.lock
Labels: skip-changelog

#852 Add check for python version
  .config/dictionary.txt
  Taskfile.yml
  tools/precheck.py
Labels: skip-changelog

#851 Update inline suggestion service name
  .config/dictionary.txt
  README.md
  package.json
  src/definitions/constants.ts
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/attributionsWebview.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/utils/data.ts
  src/features/lightspeed/utils/promiseHandlers.ts
  src/features/lightspeed/utils/webUtils.ts
  src/features/utils/lightspeed.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  src/utils/settings.ts
Labels: feature

#853 Update Ansible metadata event
  USAGE_DATA.md
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/utils/formatAnsibleMetaData.ts
Labels: enhancement

#861 Fix indent issue for one line suggestion
  .pre-commit-config.yaml
  src/features/utils/lightspeed.ts
Labels: bug

#847 Removed --system-site-package arg
  tools/test-setup.sh
Labels: skip-changelog

#866 Ansible Lightspeed e2e tests
  .config/dictionary.txt
  .github/workflows/ci.yaml
  package.json
  src/features/lightspeed/base.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  test/helper.ts
  test/testFixtures/lightspeed/playbook_1.yml
  test/testFixtures/settings.json
  test/testRunner.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/extensionUITest.ts
  test/ui-test/lightspeedUiTest.ts
  test/ui-test/uiTestHelper.ts
Labels: feature, skip-changelog

#864 Improve test-setup.sh
  tools/test-setup.sh
Labels: skip-changelog
