Repository ansible/vscode-ansible, pull requests merged in 2023-05, with the labels that each got.

#871 Easy discovery of Python interpreter and Ansible executables
  .config/dictionary.txt
  package.json
  src/definitions/constants.ts
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/pythonMetadata.ts
  src/features/utils/python.ts
  src/features/utils/setPythonInterpreter.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  src/utils/registerCommands.ts
  src/utils/settings.ts
  yarn.lock
Labels: feature

#875 Fix regex to match trigger for lightspeed suggestion (#874)
  package.json
  src/features/lightspeed/inlineSuggestions.ts
  test/helper.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  yarn.lock
Labels: bug

#857 Add error message for invalid playbook
  src/features/lightspeed/utils/data.ts
Labels: bug

#876 Add logic for conditional Authentication Provider registration
  src/extension.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/utils/settings.ts
Labels: bug

#877 Add logic for conditional Authentication Provider registration
  src/extension.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/utils/settings.ts
Labels: bug

#883 Add ability to select and set cursor on vars
  src/features/lightspeed/inlineSuggestions.ts
  src/features/utils/lightspeed.ts
Labels: feature

#892 Update inline suggestion trigger condition (#890)
  src/features/lightspeed/inlineSuggestions.ts
  test/helper.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug, AAP

#891 Update status-bar items
  package.json
  src/features/ansibleMetaData.ts
  src/features/pythonMetadata.ts
  yarn.lock
Labels: bug

#893 Update minor version
  package.json
Labels: skip-changelog

#896 Add information message for inline suggestion trigger command
  src/features/lightspeed/inlineSuggestions.ts
Labels: bug

#901 Update attributionsWebview.ts
  src/features/lightspeed/attributionsWebview.ts
Labels: bug

#903 Prepare for release v2.2 stable
  package.json
Labels: skip-changelog

#902 Add support for tox-ansible plugin test discovery
  .config/dictionary.txt
  package.json
  src/extension.ts
  src/features/ansibleTox/constants.ts
  src/features/ansibleTox/controller.ts
  src/features/ansibleTox/provider.ts
  src/features/ansibleTox/runner.ts
  src/features/ansibleTox/utils.ts
Labels: enhancement
