Repository ansible/vscode-ansible, pull requests merged in 2023-03, with the labels that each got.

#786 support v4
  src/features/utils/wisdom.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: enhancement

#787 Correct rulebook glob path
  package.json
Labels: bug

#791 Correct arch detection logic
  .config/dictionary.txt
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: skip-changelog

#790 Update code to return snippet string during completion of tasks
  src/features/utils/wisdom.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: enhancement

#794 Temporary make macos testing non-voting
  .github/workflows/ci.yaml
Labels: skip-changelog

#793 Update inlinesuggestion request as per new payload
  src/definitions/wisdom.ts
  src/extension.ts
  src/features/utils/dateTime.ts
  src/features/utils/wisdom.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: feature, enhancement

#792 Add initial skeleton for adding oauth in view container
  images/ansible.svg
  package.json
  src/definitions/constants.ts
  src/extension.ts
  src/features/wisdom/base.ts
  src/features/wisdom/utils/oAuth.ts
  src/features/wisdom/utils/promiseHandlers.ts
  src/features/wisdom/wisdomOAuthProvider.ts
  src/treeView.ts
  yarn.lock
Labels: enhancement

#796 Update wisdom feedback to use service feedback API and changes
  src/definitions/constants.ts
  src/definitions/wisdom.ts
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/utils/data.ts
  src/features/utils/dateTime.ts
  src/features/utils/wisdom.ts
  src/features/wisdom/api.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: feature

#797 Enable authentication for wisdom service
  src/definitions/constants.ts
  src/extension.ts
  src/features/wisdom/api.ts
  src/features/wisdom/base.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: feature

#798 Update extension settings for inline suggestions
  src/interfaces/extensionSettings.ts
  src/settings.ts
Labels: feature

#801 Update yarn lock file
  yarn.lock
Labels: bug

#800 typo in wisdomOAuthProvider.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug

#802 Handle trailing slash in wisdom base uri
  src/features/wisdom/api.ts
  src/features/wisdom/utils/webUtils.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug

#803 Fix indentation on moving to next line
  .config/dictionary.txt
  ansible-language-configuration.json
Labels: bug

#804 Add check for authenticated user before sending feedback request
  src/features/wisdom/api.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug

#807 Add activity tracker id from wisdom user interaction
  src/definitions/wisdom.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: enhancement

#811 Update dependencies
  .pre-commit-config.yaml
  package.json
  yarn.lock
Labels: skip-changelog

#810 Ignore errors from feedback API
  src/features/wisdom/api.ts
Labels: bug

#817 Cache containers only on macos
  .github/workflows/ci.yaml
Labels: skip-changelog

#821 Fix improper indentation while copying
  ansible-language-configuration.json
Labels: bug

#820 Inline suggestion improvements (#820)Co-authored-by: Ganesh Nalawade <ganesh634@gmail.com>
  src/definitions/constants.ts
  src/extension.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: bug

#825 Downgrade Redhat telemetry package because of ES module incompatibility
  package.json
  src/utils/telemetryUtils.ts
  yarn.lock
Labels: bug

#824 Minor OAuth fixes
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug

#826 Update Project Wisdom Name
  src/features/wisdom/api.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
  src/features/wisdom/utils/webUtils.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug

#827 Add support for training source matches
  src/definitions/constants.ts
  src/definitions/wisdom.ts
  src/extension.ts
  src/features/wisdom/api.ts
  src/features/wisdom/attributionsWebview.ts
  src/features/wisdom/base.ts
  src/features/wisdom/inlineSuggestions.ts
Labels: enhancement

#828 Show informational message when inline suggestion is empty
  src/features/wisdom/inlineSuggestions.ts
Labels: bug

#829 Update wisdom base path
  src/settings.ts
Labels: bug

#823 To add the support for Wisdom api versioning
  src/definitions/constants.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: feature

#830 Add versioning for match API
  src/definitions/constants.ts
Labels: bug

#831 Upgrade uuid
  package.json
  yarn.lock
Labels: skip-changelog

#832 Upgrade glob and adopt new APIs
  package.json
  test/index.ts
  yarn.lock
Labels: skip-changelog

#833 Update packages to sync with ALS
  package.json
  yarn.lock
Labels: skip-changelog

#834 Fix unnecessary call to feedback API
  src/features/wisdom/inlineSuggestions.ts
Labels: bug

#835 More Project Wisdom renaming
  src/features/wisdom/api.ts
  src/features/wisdom/base.ts
  src/features/wisdom/wisdomOAuthProvider.ts
Labels: bug
