Repository ansible/vscode-ansible, pull requests merged in 2023-12, with the labels that each got.

#1026 CI fixes
  .github/workflows/ci.yaml
  Taskfile.yml
  test/testRunner.ts
Labels: skip-changelog

#1029 GHA: don't assume go-task spawn a subshell to run the commands
  Taskfile.yml
Labels: skip-changelog

#1024 lightspeed: use the code value from the 403
  src/features/lightspeed/api.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/webUtils.ts
  src/interfaces/lightspeed.ts
Labels: enhancement

#1028 lightspeed: a unit-test for the error handling
  .github/workflows/coverage.yml
  .pre-commit-config.yaml
  jest.config.js
  package.json
  src/features/lightspeed/api.ts
  src/features/lightspeed/handle_api_error.ts
  test/units/lightspeed/handle_api_error.test.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#1032 Handle spaces in file path
  src/features/runner.ts
Labels: bug

#1031 unit-tests: move from Jest to Mocha
  .gitignore
  .mocharc.yml
  cspell.config.yaml
  jest.config.js
  package.json
  test/units/lightspeed/handle_api_error.test.ts
  yarn.lock
Labels: enhancement

#1012 GitHub Codespaces/code-server support
  src/features/lightspeed/lightSpeedOAuthProvider.ts
Labels: enhancement
