Repository ansible/vscode-ansible, pull requests merged in 2023-02, with the labels that each got.

#770 Add fix to remove prompt from suggestion
  src/definitions/constants.ts
  src/definitions/wisdom.ts
  src/extension.ts
  src/features/utils/wisdom.ts
  src/features/wisdom/inlineSuggestions.ts
  src/utils/telemetryUtils.ts
Labels: bug

#777 Fix devel testing
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .yarn/releases/yarn-3.3.0.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Taskfile.yml
  package.json
  tools/clone-sibling.sh
  tools/test-setup.sh
  yarn.lock
Labels: bug

#779 Install yarn 1.10.2
  package.json
  tools/clone-sibling.sh
  yarn.lock
Labels: skip-changelog

#772 Fix onEnter key bindings to work with ansible extension only
  src/definitions/constants.ts
  src/extension.ts
Labels: bug

#686 Improve setup script
  .github/workflows/ci.yaml
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#692 Show info in status-bar if a newer version of ansible-lint is available
  src/features/utils/formatAnsibleMetaData.ts
Labels: enhancement

#781 Update jenkins URL
  doc/development.md
Labels: skip-changelog

#784 Correct changelog
  CHANGELOG.md
Labels: bug
