Repository ansible/vscode-ansible, pull requests merged in 2023-06, with the labels that each got.

#911 Fix notification for lightspeed login after the setting is disabled
  src/features/lightspeed/base.ts
Labels: bug

#916 Update package.json
  package.json
Labels: skip-changelog

#924 Lightspeed UI feedback and sentiment
  .config/dictionary.txt
  .eslintrc.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  .vscodeignore
  CHANGELOG.md
  Taskfile.yml
  cspell.config.yaml
  media/style.css
  package.json
  src/definitions/constants.ts
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/feedbackWebviewProvider.ts
  src/features/lightspeed/feedbackWebviewViewProvider.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/feedbackView.ts
  src/features/utils/getNonce.ts
  src/features/utils/getUri.ts
  src/webview/apps/lightspeed/main.ts
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: feature, enhancement

#926 Update readme with lightspeed section
  README.md
Labels: bug, documentation

#932 Upgrade ALS to v1.1.0
  package.json
  test/testScripts/diagnostics/testYamlWithoutEE.test.ts
  yarn.lock
Labels: enhancement

#934 Make hover e2e tests fixture messages more generic
  test/testScripts/hover/testWithEE.test.ts
  test/testScripts/hover/testWithoutEE.test.ts
Labels: bug
