Repository ansible/vscode-ansible, pull requests merged in 2024-11, with the labels that each got.

#1613 Rework EE volume mount setting so default value will populate
  docs/README.md
  docs/als/settings.md
  package.json
  packages/ansible-language-server/src/interfaces/extensionSettings.ts
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/services/settingsManager.ts
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/tools/settings-doc-generator.ts
Labels: bug

#1487 Remove redundant activation events
  package.json
Labels: bug

#1620 More deps
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1621 Update typescript to 5.6
  Taskfile.yml
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1623 More deps
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1626 Configure dependabot strategy
  .github/dependabot.yml
Labels: skip-changelog

#1627 Update ini dependency to v5
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1629 Start using nodejs 20
  .github/workflows/ci.yaml
  .github/workflows/dedupe.yml
  .tool-versions
  package.json
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/package.json
Labels: bug

#1631 Update glob to v11
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1633 Update sinon, marked and minimatch
  package.json
  yarn.lock
Labels: skip-changelog

#1635 updates for eslint strict type check
  .pre-commit-config.yaml
  eslint.config.mjs
  package.json
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/utils/docsParser.ts
  packages/ansible-language-server/src/utils/imagePuller.ts
  packages/ansible-language-server/src/utils/yaml.ts
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/features/utils/applyFileInspectionForKeywords.ts
  src/features/utils/syntaxHighlighter.ts
  src/utils/executionEnvironment.ts
  test/index.ts
  test/lib/nyc.d.ts
  test/ui-test/uiTestHelper.ts
  yarn.lock
Labels: skip-changelog

#1640 Update typescript-eslint
  package.json
  yarn.lock
Labels: skip-changelog

#1643 Bump @types/express from 4.17.21 to 5.0.0 and express from 4.21.1 to 5.0.1
  package.json
  test/mockLightspeedServer/server.ts
  yarn.lock
Labels: skip-changelog, dependencies

#1645 Bump @types/node from 20.17.6 to 22.9.0
  package.json
  packages/ansible-language-server/package-lock.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog, dependencies

#1398 package.json: remove the compile-withserver target
  docs/development.md
  package.json
Labels: skip-changelog

#1261 Simplify withInterpreter signature
  packages/ansible-language-server/src/utils/commandRunner.ts
  packages/ansible-language-server/src/utils/misc.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  src/extension.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/utils.ts
  src/features/runner.ts
  src/features/utils/commandRunner.ts
Labels: skip-changelog

#1647 Enable eslint caching
  .config/dictionary.txt
  .gitignore
  .pre-commit-config.yaml
Labels: skip-changelog

#1649 test: use test-launch.sh to run the tests
  .config/dictionary.txt
  .github/workflows/ci.yaml
  Taskfile.yml
  package.json
  test/README.md
  tools/coverage-all.sh
  tools/run-ui-test-with-mock-lightspeed-server.sh
  tools/test-launcher.sh
  yarn.lock
Labels: enhancement

#1641 AAP-34738: Lightspeed Identify the collections available in the current workspace
  .config/dictionary.txt
  .gitignore
  .pre-commit-config.yaml
  src/features/lightspeed/roleGeneration.ts
  src/features/lightspeed/utils/scanner.ts
  test/units/lightspeed/utils/samples/collections/ansible_collections/community/broken_MANIFEST/MANIFEST.json
  test/units/lightspeed/utils/samples/collections/ansible_collections/community/dummy/galaxy.yml
  test/units/lightspeed/utils/samples/collections/ansible_collections/community/empty/README
  test/units/lightspeed/utils/samples/collections/ansible_collections/community/general/MANIFEST.json
  test/units/lightspeed/utils/samples/collections/ansible_collections/empty/README
  test/units/lightspeed/utils/samples/collections/ansible_collections/openstack/cloud/MANIFEST.json
  test/units/lightspeed/utils/samples/collections/ansible_collections/virt_lightning/virt_lightning/MANIFEST.json
  test/units/lightspeed/utils/scanner.test.ts
Labels: enhancement

#1612 AAP-33750: lightspeed/role: add the role_name field
  src/features/lightspeed/roleGeneration.ts
Labels: enhancement

#1655 test-launcher.sh: minor adjustments
  tools/test-launcher.sh
Labels: skip-changelog

#1656 tools/helper --package: ensure out/log directory exists
  tools/helper
Labels: skip-changelog

#1657 test-launcher: rebuild the .vsix on the fly if it's outdated
  tools/test-launcher.sh
Labels: skip-changelog

#1660 Update vscode-extension-tester to 8.9.0
  package.json
  test/ui-test/contentCreatorUiTest.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedUiTest.ts
  test/ui-test/uiTestHelper.ts
  test/ui-test/walkthroughUiTest.ts
  test/ui-test/welcomePageUITest.ts
  yarn.lock
Labels: bug

#1667 Fix command used in the playbook sidebar link
  src/features/quickLinks/quickLinksView.ts
Labels: skip-changelog

#1663 Replace force param with overwrite in creator webviews
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/types.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1673 lightpseed: only show the "Explain with Lightspeed" when needed
  package.json
Labels: bug

#1675 AAP-35216: mockLightspeedServer: mock the new roleGen end-point
  test/mockLightspeedServer/playbookGeneration.ts
  test/mockLightspeedServer/roleGeneration.ts
  test/mockLightspeedServer/server.ts
Labels: skip-changelog

#1670 Ansible Lightspeed Verizon RFE - Open multiple Playbook Gen wizards
  src/features/lightspeed/playbookGeneration.ts
  test/ui-test/lightspeedUiTest.ts
Labels: enhancement

#1683 AAP-35216: lightspeed: Rename PlaybookGenerationActionType
  .sonarcloud.properties
  src/definitions/lightspeed.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/interfaces/lightspeed.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1686 AAP-16652: Lightspeed: support multi-line prompt for multitasks suggestions
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/utils/multiLinePromptForMultiTasks.ts
  test/units/lightspeed/utils/multiLinePromptForMultiTasks.test.ts
Labels: enhancement
