Repository ansible/vscode-ansible, pull requests merged in 2024-12, with the labels that each got.

#1690 update vscode-extension-tester to 8.10.0
  package.json
  yarn.lock
Labels: minor

#1687 dirty.sh: silently exit 0 when run from within VSCode
  tools/dirty.sh
Labels: minor

#1681 Add a webview to generate a devfile without ansible-creator
  .config/dictionary.txt
  .pre-commit-config.yaml
  .vscodeignore
  media/baseStyles/baseFormStyle.css
  media/contentCreator/createDevfilePageStyle.css
  package.json
  resources/contentCreator/createDevfile/devfile-template.txt
  src/extension.ts
  src/features/contentCreator/createDevfilePage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createDevfilePageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  tools/compare_devfile.sh
  webpack.config.ts
Labels: minor

#1689 Playbook Generation: Add "Are you sure?" Confirmation for Reset Button
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
Labels: enhancement

#1700 Revert "Playbook Generation: Add "Are you sure?" Confirmation for Reset Button"
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
Labels: enhancement

#1703 Autofill devfile project name into the webview text field
  src/features/contentCreator/createDevfilePage.ts
  src/webview/apps/contentCreator/createDevfilePageApp.ts
Labels: skip-changelog

#1704 Add a link to extension settings in the quick links bar
  src/features/quickLinks/quickLinksView.ts
Labels: skip-changelog

#1688 AAP-36992: ui-test: isolate each tests
  .github/workflows/ci.yaml
  .mocharc.yml
  test/mockLightspeedServer/openUrl.ts
  test/mockLightspeedServer/server.ts
  test/testFixtures/settings.json
  test/ui-test/allTestsSuite.ts
  test/ui-test/contentCreatorUiTest.ts
  test/ui-test/contentCreatorUiTestNoCreatorTest.ts
  test/ui-test/extensionUITest.ts
  test/ui-test/lightspeedAuthUiTest.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedUiTest.ts
  test/ui-test/lightspeedUiTestActiveBarTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoLSTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenNotAvailableTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/lightspeedUiTestStatusBarAndExplorerViewNoLSTest.ts
  test/ui-test/lightspeedUiTestStatusBarAndExplorerViewTest.ts
  test/ui-test/terminalUiTest.ts
  test/ui-test/walkthroughUiTest.ts
  test/ui-test/welcomePageUITest.ts
  tools/test-launcher.sh
Labels: minor

#1705 Add a `new` badge to items in the quick links view
  media/quickLinks/quickLinksStyle.css
  src/features/quickLinks/quickLinksView.ts
Labels: skip-changelog

#1685 AAP-35216: integrate the roleGen with its new API endpoint
  .vscodeignore
  media/roleGeneration/style.css
  src/features/lightspeed/api.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/features/lightspeed/utils/errors.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/roleGeneration/main.ts
  test/ui-test/lightspeedRoleGenTest.ts
  tools/test-launcher.sh
Labels: minor

#1706 Fix create button enablement when autofilling project name
  src/webview/apps/contentCreator/createDevfilePageApp.ts
Labels: skip-changelog

#1701 Add "Are you sure?" Confirmation for Reset Button
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  src/webview/apps/lightspeed/roleGeneration/main.ts
  test/ui-test/lightspeedRoleGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoLSTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/uiTestHelper.ts
Labels: enhancement

#1710 Add vscodeignore entries for welcome page
  .vscodeignore
  src/features/welcomePage/index.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
Labels: bug

#1718 Update name of ui test upload from unit to ui
  .github/workflows/ci.yaml
Labels: skip-changelog

#1715 Disable explanation thumbs up and thumbs down buttons after selection
  src/webview/apps/lightspeed/playbookExplanation/main.ts
  test/ui-test/lightspeedUiTestPlaybookExpTest.ts
Labels: enhancement

#1717 Revert "Add “Generate a Playbook” Button to Side Panel"
  src/features/lightspeed/utils/explorerView.ts
  src/webview/apps/lightspeed/explorer/main.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedUiTestExplorerTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/walkthroughUiTest.ts
Labels: skip-changelog

#1724 AAP-37422: Empty line at the top of the file break completion
  src/features/lightspeed/utils/multiLinePromptForMultiTasks.ts
  test/units/lightspeed/utils/multiLinePromptForMultiTasks.test.ts
Labels: bug

#1726 Check ansible-creator version when initializing a collection project
  src/definitions/constants.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/utils.ts
Labels: bug

#1728 Workaround for codecov-action bug with oidc
  .github/workflows/ci.yaml
Labels: skip-changelog

#1707 tools/test-launcher.sh: drop the -x flag
  tools/test-launcher.sh
Labels: skip-changelog

#1727 Add Webview to scaffold sample execution-environment.yml file using creator add subcommand
  .sonarcloud.properties
  .vscodeignore
  codecov.yml
  media/contentCreator/createSampleExecutionEnvPageStyle.css
  package.json
  src/definitions/constants.ts
  src/extension.ts
  src/features/contentCreator/createSampleExecutionEnvPage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createSampleExecutionEnvPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  webpack.config.ts
Labels: enhancement

#1731 Increase node memory on GH runners
  .envrc
Labels: bug

#1733 Add --no-overwrite param to execution-environment creator command in the webview
  src/definitions/constants.ts
  src/features/contentCreator/createSampleExecutionEnvPage.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: skip-changelog

#1708 Add Webview for Generating a Devcontainer without ansible-creator
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  .sonarcloud.properties
  .vscodeignore
  codecov.yml
  media/contentCreator/createDevcontainerPageStyle.css
  package.json
  resources/contentCreator/createDevcontainer/.devcontainer/devcontainer-template.txt
  resources/contentCreator/createDevcontainer/.devcontainer/docker/devcontainer-template.txt
  resources/contentCreator/createDevcontainer/.devcontainer/podman/devcontainer-template.txt
  src/definitions/constants.ts
  src/extension.ts
  src/features/contentCreator/createDevcontainerPage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createDevcontainerPageApp.ts
  test/ui-test/contentCreatorUiTestNoCreatorTest.ts
  tools/compare_devcontainer.sh
  webpack.config.ts
Labels: enhancement

#1729 Add a webview to scaffold plugins through creator add subcommand
  .sonarcloud.properties
  .vscodeignore
  codecov.yml
  media/contentCreator/addPluginPageStyle.css
  package.json
  src/extension.ts
  src/features/contentCreator/addPluginPage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/addPluginPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  webpack.config.ts
Labels: enhancement

#1741 Ensure NODE_OPTIONS is the same on local and CI
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  tools/precheck.py
Labels: skip-changelog

#1742 Update outdated URL to ALS settings
  docs/als/README.md
Labels: skip-changelog
