Repository ansible/vscode-ansible, pull requests merged in 2024-02, with the labels that each got.

#1071 Minor testing fixes
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
  tools/test-setup.sh
Labels: skip-changelog

#1076 enable lightspeed connect when ready
  package.json
  src/extension.ts
Labels: bug

#1077 handle invalid python interpreter path
  src/extension.ts
  src/features/pythonMetadata.ts
Labels: bug

#1085 avoid an exception during init if 'roles' is not a directory
  package.json
  src/features/lightspeed/base.ts
  src/features/lightspeed/utils/data.ts
  src/features/lightspeed/utils/readVarFiles.ts
  src/features/lightspeed/utils/updateRolesContext.ts
  src/features/lightspeed/utils/watchers.ts
  test/units/lightspeed/utils/updateRolesContext.ts
  yarn.lock
Labels: bug

#1086 update trial expiry message
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: skip-changelog

#1067 Integrate code coverage & mock Lightspeed server into CI
  .github/workflows/ci.yaml
  Taskfile.yml
  package.json
  src/features/lightspeed/contentMatchesWebview.ts
  test/index.ts
  test/mockLightspeedServer/server.ts
  test/units/lightspeed/contentmatches.test.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, dependencies

#1078 Lightspeed VSCode extension: Analytics telemetry opting-out support
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/utils/feedbackView.ts
  src/interfaces/extensionSettings.ts
Labels: enhancement

#1082 handle command in python interpreter path
  src/features/pythonMetadata.ts
Labels: bug

#1081 Update vscode-extension-tester to 7.0.0
  package.json
  test/ui-test/extensionUITest.ts
  yarn.lock
Labels: skip-changelog

#1074 Lightspeed multitask inference e2e test cases
  test/helper.ts
  test/mockLightspeedServer/completion.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: skip-changelog

#1091 Prepare for 2.11 release
  CHANGELOG.md
  package.json
Labels: skip-changelog

#1090 Reject feedback API for unlicensed users after disabling tech preview
  src/features/lightspeed/api.ts
  test/mockLightspeedServer/feedback.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
Labels: AAP, enhancement

#1094 Update CI job to assign auto server number for xvfb execution
  .config/dictionary.txt
  Taskfile.yml
Labels: bug

#1095 Unbound variable error in language server CI jobs
  package.json
  tools/coverage-all.sh
Labels: bug

#1098 Update node 18 in the CI
  .tool-versions
Labels: skip-changelog

#1099 avoid duplicated suggestionFeedback event
  src/features/lightspeed/inlineSuggestions.ts
Labels: bug

#1097 Update lightspeed doc link in README
  README.md
Labels: documentation, minor

#1109 Copilot tab completion does not work with v2.12 extension
  src/features/lightspeed/inlineSuggestions.ts
  test/testFixtures/lightspeed/playbook_2.yml
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug
