Repository ansible/vscode-ansible, pull requests merged in 2024-07, with the labels that each got.

#1397 Respect ${workspaceFolder} in PythonInterpreterManager
  src/features/pythonMetadata.ts
Labels: bug

#1414 Handle exceptions raised from uncorrelated x-request-id headers
  packages/ansible-language-server/src/errors.ts
  packages/ansible-language-server/test/utils/handleApiError.test.ts
Labels: enhancement

#1416 Update diagnostics tests
  test/testFixtures/diagnostics/ansible/without_ee/playbook_2.yml
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
Labels: skip-changelog

#1409 Show a pop-up trial Info message if the user has no commercial offer on Lightspeed
  package.json
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/oneClickTrial.ts
  test/mockLightspeedServer/completion.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/feedback.ts
  test/mockLightspeedServer/generations.ts
  test/mockLightspeedServer/me.ts
  test/mockLightspeedServer/openUrl.ts
  test/mockLightspeedServer/server.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedAuthUiTest.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/uiTestHelper.ts
  yarn.lock
Labels: enhancement

#1417 Update ALS diagnostics tests
  packages/ansible-language-server/test/fixtures/diagnostics/lint_errors.yml
  packages/ansible-language-server/test/providers/validationProvider.test.ts
Labels: skip-changelog

#1395 Lightspeed exp/gen: trigger a timeout after 28s
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/errors.ts
  packages/ansible-language-server/src/utils/handleApiError.ts
Labels: bug

#1422 Playbook Generation UI glitches
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
Labels: bug

#1424 Modify the logic to set the pre-release version number
  tools/helper
Labels: skip-changelog

#1429 Disable Generate Playbook button when outline is empty
  src/webview/apps/common/editableList.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/units/lightspeed/editableList.test.ts
Labels: bug

#1426 Support permission_denied__can_apply_for_trial error code
  packages/ansible-language-server/src/errors.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/oneClickTrial.ts
  test/mockLightspeedServer/completion.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/feedback.ts
  test/mockLightspeedServer/generations.ts
  test/mockLightspeedServer/server.ts
Labels: skip-changelog

#1431 Update outline only after successful playbook generation
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/generations.ts
  test/ui-test/lightspeedUiTest.ts
Labels: bug

#1425 AAP 26574 - expose markdown content
  src/definitions/lightspeed.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/utils/explorerView.ts
  test/mockLightspeedServer/meMarkdown.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/testLightspeedUser.test.ts
Labels: enhancement

#1423 lightspeed: drop permission_denied__org_ready_user_has_no_seat error check
  packages/ansible-language-server/src/errors.ts
  packages/ansible-language-server/test/utils/handleApiError.test.ts
Labels: minor

#1434 Fix helper for stable releases
  tools/helper
Labels: skip-changelog

#1432 Handle HAP detected in playbook gen and explanation
  packages/ansible-language-server/src/errors.ts
  packages/ansible-language-server/test/utils/handleApiError.test.ts
Labels: enhancement

#1436 Message for no access error is displayed at every other attempt for code completion
  src/features/lightspeed/api.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
Labels: bug

#1437 log response data to console when /me request fails
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
Labels: minor

#1445 Minor testing fixes
  .config/dictionary.txt
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: skip-changelog

#1447 lightspeed trial: point direct on /trial
  src/extension.ts
Labels: skip-changelog

#1449 Remove one of two examples for Lightspeed completion tests
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: skip-changelog

#1453 "undefined" is displayed in sidebar when Lightspeed is not enabled
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  test/ui-test/lightspeedUiTest.ts
Labels: bug

#1457 Remove ` tsdoc.json` (has space in name)
   tsdoc.json
Labels: skip-changelog

#1458 Skip Lightspeed Inline Completion "keeping typing" test case temporarily
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: skip-changelog

#1441 Add ansible-playbook argument setting option
  .config/requirements.in
  docs/README.md
  package.json
  package.nls.json
  src/extension.ts
  src/features/runner.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  test/testFixtures/settings.json
  test/testFixtures/terminal/playbook.yml
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedUiTest.ts
  test/ui-test/terminalUiTest.ts
  test/ui-test/uiTestHelper.ts
Labels: enhancement

#1461 als: avoid unnecessary logging related to successful container removal
  .vscode/settings.json
  packages/ansible-language-server/.mocharc.yml
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/test/providers/completionProvider.test.ts
Labels: skip-changelog

#1459 Add development docs for the extension
  .config/dictionary.txt
  .pre-commit-config.yaml
  docs/development/additional_resources.md
  docs/development/debug_extension.md
  docs/development/extension_code_structure.md
  docs/development/main.md
  docs/development/media/extension-code-structure.png
  docs/development/media/server-code-structure.png
  docs/development/media/webview-communication-flow.png
  docs/development/media/webview-in-extension.png
  docs/development/media/webview-lifecycle.png
  docs/development/project_structure.md
  docs/development/server_code_structure.md
  docs/development/test_code.md
  docs/development/webview_guide.md
  mkdocs.yml
Labels: enhancement

#1465 Add link for the developer docs
  docs/README.md
Labels: enhancement

#1466 Update dependencies
  package.json
  yarn.lock
Labels: skip-changelog

#1455 Support MOCHA_INVERT envvar in E2E test
  test/index.ts
Labels: skip-changelog

#1269 Add file icon
  images/ansible-fileicon.svg
  package.json
Labels: enhancement

#1470 lightspeed: adjust the trial pop-up message
  src/features/lightspeed/utils/oneClickTrial.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
Labels: minor

#1471 test: update jsdom
  .pre-commit-config.yaml
  package.json
  src/webview/apps/common/editableList.ts
  yarn.lock
Labels: skip-changelog

#1469 Make als tests recognize SKIP_DOCKER and SKIP_PODMAN
  .config/dictionary.txt
  .envrc
  .github/workflows/ci.yaml
  .nycrc.yml
  packages/ansible-language-server/.nycrc.yml
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/package.json
  packages/ansible-language-server/test/fixtures/completion/dynamic_inventory.py
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/index.ts
  packages/ansible-language-server/test/rootMochaHooks.ts
  packages/ansible-language-server/tsconfig.json
  tools/convert-als-coverage-lcov.sh
Labels: skip-changelog

#1446 Refactor GHA build steps
  .c8rc
  .config/Containerfile
  .config/dictionary.txt
  .github/workflows/ci.yaml
  Taskfile.yml
  codecov.yml
  package.json
  packages/ansible-language-server/package.json
  pyproject.toml
  test/testRunner.ts
Labels: skip-changelog
