Repository ansible/vscode-ansible, pull requests merged in 2024-03, with the labels that each got.

#1105 No inlineSuggestionFeedback if user accepted it on widget
  src/extension.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/helper.ts
  test/mockLightspeedServer/me.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1075 Content Matches E2E test
  package.json
  src/features/lightspeed/base.ts
  test/helper.ts
  test/mockLightspeedServer/contentmatches.ts
  test/mockLightspeedServer/server.ts
Labels: skip-changelog

#1107 Reject pending suggestion if text selection changes
  src/extension.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/helper.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1111 send ansible extension version in lightspeed requests
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
Labels: minor

#1112 Push disposals to context.subscriptions
  src/extension.ts
Labels: skip-changelog

#1113 Send IGNORED suggestion feedback when active editor/window is changed
  src/extension.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/testFixtures/lightspeed/playbook_3.yml
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1088 Re-enable Lightspeed UI tests
  src/definitions/lightspeed.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/webUtils.ts
  src/interfaces/lightspeed.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedUiTest.ts
Labels: bug

#1115 Do not send ACCEPTED feedback from commit handler
  src/extension.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1118 Fix terminal color and navigator command execution
  src/features/runner.ts
  src/features/utils/commandRunner.ts
Labels: bug

#1116 Send IGNORED feedback if feedback was pending
  src/features/lightspeed/inlineSuggestions.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: minor

#1119 Prepare for 2.13 release
  CHANGELOG.md
  package.json
Labels: skip-changelog

#1123 Add example to show feature support for playbook adjacent collection
  examples/collections/ansible_collections/my_namespace/my_collection/galaxy.yml
  examples/collections/ansible_collections/my_namespace/my_collection/plugins/modules/my_test.py
  examples/playbook_for_adjacent_collection.yml
Labels: enhancement

#1124 Update ack.yml
  .github/workflows/ack.yml
Labels: skip-changelog

#1127 Add coverage token
  .github/workflows/ci.yaml
Labels: skip-changelog

#1126 Set environment variables at step level using matrix properties in GitHub Actions
  .github/workflows/ci.yaml
Labels: skip-changelog

#1120 Avoid mocha slow (red) markers on test executions
  .mocharc.yml
Labels: skip-changelog

#1117 Add comment crediting Ansible Lightspeed to suggestion ghost text
  README.md
  package.json
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: minor

#1122 Address 'User not authorized to access Ansible Lightspeed' when request is blocked by CloudFront
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: bug, AAP

#1129 Do not send inlineSuggestionFeedback when completion API returns a non-200 status
  src/features/lightspeed/api.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/helper.ts
  test/mockLightspeedServer/completion.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1131 AAP-21329: Capture relevant model in feedback events
  src/features/lightspeed/api.ts
  src/interfaces/lightspeed.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
Labels: enhancement

#1165 AAP-19228: Refactor error handling in wisdom service and vscode extension
  .gitignore
  src/features/lightspeed/api.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: enhancement

#1171 Add a comment to a Lightspeed test case
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
Labels: documentation, skip-changelog

#1169 Use python3 executable
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#1162 Reduce e2e test activation wait time to 2 secs
  package.json
  test/helper.ts
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
  test/testScripts/diagnostics/testYamlWithoutEE.test.ts
  test/testScripts/outsideWorkspace/testExtensionForFilesOutsideWorkspace.test.ts
  yarn.lock
Labels: skip-changelog

#1161 Fix Jenkins build failure
  Jenkinsfile
  Taskfile.yml
  package.json
Labels: skip-changelog

#1173 Configure dependabot for npm
  .github/dependabot.yml
  .gitignore
Labels: skip-changelog

#1177 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#1181 Archive ansible-language-server artifact
  .github/workflows/ci.yaml
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#1183 Change venv location and make use of direnv on gha
  .envrc
  .github/workflows/ci.yaml
  .tool-versions
  Taskfile.yml
  packages/ansible-language-server/.envrc
  packages/ansible-language-server/.vscode/settings.json
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/tools/test-setup.sh
  tools/test-setup.sh
Labels: skip-changelog
