Repository ansible/vscode-ansible, pull requests merged in 2024-01, with the labels that each got.

#1040 fix check for no seat assigned
  src/features/lightspeed/utils/webUtils.ts
Labels: bug

#1041 unit-test coverage for contentMatchesWebview
  .config/dictionary.txt
  .github/workflows/coverage.yml
  package.json
  test/units/lightspeed/contentmatches.test.ts
  yarn.lock
Labels: enhancement

#1047 Add Tami to approver list
  .config/dictionary.txt
  Jenkinsfile
Labels: skip-changelog

#1048 Rename files and vars to use camel case inline with the naming conven…
  src/features/lightspeed/api.ts
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/contentmatches.test.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: minor

#1051 Ignore a webpack warning from vscode-languageserver-textdocument
  .github/workflows/ci.yaml
  package.json
  src/utils/telemetryUtils.ts
  webpack.config.ts
Labels: bug, AAP

#1046 Show model ID to be used in statusbar tooltip
  src/definitions/lightspeed.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/statusBar.ts
Labels: feature, enhancement

#1050 Do not send duplicated inline suggestion feedback
  src/features/lightspeed/api.ts
  src/features/lightspeed/inlineSuggestions.ts
Labels: bug, AAP

#1057 Prepare for 2.10 release
  .prettierrc.yaml
  CHANGELOG.md
  package.json
Labels: skip-changelog

#1056 Enable code coverage on e2e tests
  .gitignore
  package.json
  test/index.ts
  test/testRunner.ts
Labels: enhancement

#1059 lightspeed: show a proper message when the user has no seat
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: enhancement

#1055 lightspeed/inlineSuggestions: refactoring to simplify the testing
  src/extension.ts
  src/features/lightspeed/inlineSuggestion/additionalContext.ts
  src/features/lightspeed/inlineSuggestion/suggestionDisplayed.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/interfaces/lightspeed.ts
Labels: enhancement

#1062 Mock Lightspeed Server for local test execution
  package.json
  test/helper.ts
  test/mockLightspeedServer/completion.ts
  test/mockLightspeedServer/me.ts
  test/mockLightspeedServer/openUrl.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
  test/ui-test/extensionUITest.ts
  yarn.lock
Labels: enhancement

#1065 Fix build process
  .config/Containerfile
  .github/workflows/ack.yml
  .github/workflows/ci.yaml
  .github/workflows/coverage.yml
  .github/workflows/push.yml
  .gitignore
  .pre-commit-config.yaml
  .tool-versions
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#1066 Update dependencies
  package.json
  test/index.ts
  yarn.lock
Labels: skip-changelog

#1064 Show Licensed or Unlicensed for user type
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/webUtils.ts
  src/interfaces/lightspeed.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: minor, AAP

#1068 Remove untildify dependency
  package.json
  src/features/utils/ansibleCfg.ts
  yarn.lock
Labels: skip-changelog

#1069 Enable codecov reporting
  .github/workflows/ci.yaml
  .nycrc.yml
  codecov.yml
  package.json
Labels: skip-changelog

#1070 Fix two test runner issues
  test/index.ts
  test/testFixtures/diagnostics/ansible/without_ee/playbook_1.yml
  test/testFixtures/diagnostics/ansible/without_ee/playbook_2.yml
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
Labels: skip-changelog
