Repository ansible/vscode-ansible, pull requests merged in 2024-09, with the labels that each got.

#1528 Lightspeed Service to prevent users from submitting invali
  src/features/lightspeed/api.ts
  src/features/lightspeed/errors.ts
  test/units/lightspeed/utils/handleApiError.test.ts
Labels: enhancement

#1525 README: add Forum
  docs/README.md
Labels: skip-changelog

#1535 Remove `xargs` usage in EE cleanup functionality
  packages/ansible-language-server/src/services/executionEnvironment.ts
Labels: bug

#1542 Nesting commands to fix container cleanup
  Taskfile.yml
  packages/ansible-language-server/src/services/executionEnvironment.ts
Labels: bug

#1548 Clean up test-resources & ext dirs before running UI test
  Taskfile.yml
Labels: skip-changelog

#1551 Close editors before running One Click Trial UI test
  test/ui-test/lightspeedOneClickTrialUITest.ts
Labels: skip-changelog

#1545 AAP-30427: VS Code Extension settings page to take a new custom_prompt field
  package.json
  src/features/lightspeed/api.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/handleApiError.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/extensionSettings.ts
  src/interfaces/lightspeed.ts
  src/settings.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/generations.ts
  test/testFixtures/lightspeed/playbook_explanation_none.yml
  test/ui-test/lightspeedUiTest.ts
  test/units/lightspeed/utils/handleApiError.test.ts
Labels: enhancement
