Repository ansible/vscode-ansible, pull requests merged in 2024-10, with the labels that each got.

#1558 AAP-32429: VS Code Extension: Remove custom_prompt fields from Settings page
  package.json
  src/features/lightspeed/api.ts
  src/features/lightspeed/playbookExplanation.ts
  src/interfaces/lightspeed.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/generations.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1562 Pin to codecov version v4.5.0
  .github/workflows/ci.yaml
Labels: bug

#1475 Add welcome page and update the title
  media/welcomePage/style.css
  package.json
  src/extension.ts
  src/features/contentCreator/welcomePage.ts
  src/features/playbookGeneration/welcomePage.ts
  src/features/welcomePage/index.ts
  src/webview/apps/welcomePage/welcomePageApp.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedUiTest.ts
  test/ui-test/welcomePageUITest.ts
  webpack.config.ts
Labels: enhancement

#1568 AAP-32403: Lightspeed: Playbook generation: Handle "warnings" in response
  media/playbookGeneration/playbookGeneration.css
  media/playbookGeneration/style.css
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/generations.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1577 fix deprecation warning for ANSIBLE_COLLECTIONS_PATH
  packages/ansible-language-server/test/helper.ts
  test/helper.ts
  test/testScripts/diagnostics/testYamlWithoutEE.test.ts
Labels: bug

#1576 Pin codecov action to v4.5.0 and update dependabot.yml to ignore v4.6.0
  .github/dependabot.yml
  .github/workflows/ci.yaml
Labels: skip-changelog

#1573 Update yarn and eslint
  .config/Containerfile
  .pre-commit-config.yaml
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.5.0.cjs
  .yarnrc.yml
  package.json
  packages/ansible-language-server/.config/Dockerfile
Labels: skip-changelog

#1561 Enable eslint strict type checks
  eslint.config.mjs
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/providers/completionProvider.ts
  packages/ansible-language-server/src/services/ansibleInventory.ts
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/services/settingsManager.ts
  packages/ansible-language-server/src/services/validationManager.ts
  packages/ansible-language-server/src/utils/docsFormatter.ts
  packages/ansible-language-server/src/utils/getAnsibleMetaData.ts
  packages/ansible-language-server/src/utils/yaml.ts
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/index.ts
  packages/ansible-language-server/test/rootMochaHooks.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  src/features/ansibleTox/controller.ts
  src/features/ansibleTox/runner.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/feedbackWebviewProvider.ts
  src/features/lightspeed/feedbackWebviewViewProvider.ts
  src/features/lightspeed/handleApiError.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/data.ts
  src/features/lightspeed/utils/promiseHandlers.ts
  src/features/runner.ts
  src/features/utils/ansible.ts
  src/features/utils/ansibleCfg.ts
  src/features/utils/applyFileInspectionForKeywords.ts
  src/features/utils/applyModelines.ts
  src/features/vault.ts
  src/features/welcomePage/index.ts
  src/utils/telemetryUtils.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  src/webview/apps/welcomePage/welcomePageApp.ts
  test/helper.ts
  test/index.ts
  test/mockLightspeedServer/contentmatches.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  test/ui-test/extensionUITest.ts
  test/ui-test/lightspeedAuthUiTest.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/units/lightspeed/editableList.test.ts
Labels: bug

#1575 Cleaning up media assets after the walkthrough changes
  .vscodeignore
  media/walkthroughs/createAnsibleEnv/adt-components.md
  media/walkthroughs/createAnsibleEnv/all-adt-components.png
  media/walkthroughs/createAnsibleEnv/language-selector.png
  media/walkthroughs/createAnsibleEnv/language-statusbar.png
  media/walkthroughs/createAnsibleEnv/open-folder.png
  media/walkthroughs/createAnsibleEnv/selectAnsibleLanguage.md
  media/walkthroughs/gettingStarted/adt-components.png
  media/walkthroughs/unusedResources/all-adt-tools.png
  media/walkthroughs/unusedResources/ansible-env/environment-statusbar.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-env copy.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-env.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-lint-env copy.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-lint-env.png
  media/walkthroughs/unusedResources/ansible-env/ok-env copy.png
  media/walkthroughs/unusedResources/ansible-env/ok-env.png
  media/walkthroughs/unusedResources/ansible-extension-settings.png
  media/walkthroughs/unusedResources/ansible-features/ansible-lint-crop.gif
  media/walkthroughs/unusedResources/ansible-features/go-to-definition-crop.gif
  media/walkthroughs/unusedResources/ansible-features/hover-documentation-module-crop.png
  media/walkthroughs/unusedResources/ansible-features/smart-completions-crop.gif
  media/walkthroughs/unusedResources/ansible-features/syntax-highlighting-crop.png
  media/walkthroughs/unusedResources/ansibleEnvironment.md
  media/walkthroughs/unusedResources/language-selector.png
  media/walkthroughs/unusedResources/languageFeatures.md
  media/walkthroughs/unusedResources/learn-more.png
  media/walkthroughs/unusedResources/run-ansible-playbook.png
  package.json
Labels: minor

#1583 Fix an incorrectly named media file for Create an Ansible Env walkthrough
  media/walkthroughs/createAnsibleEnv/all-adt-components.png
  media/walkthroughs/discoverAdt/all-adt-components.png
  package.json
Labels: skip-changelog

#1582 Update creator webviews to reflect ansible-creator CLI changes
  media/contentCreator/createAnsibleProjectPageStyle.css
  package.json
  src/definitions/constants.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/types.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/contentCreatorUiTest.ts
  test/units/contentCreator/utilities.test.ts
  yarn.lock
Labels: minor

#1590 Update ansible-creator version required for new CLI command
  src/definitions/constants.ts
Labels: bug

#1592 Add ansible file icon to .vscodeignore
  .config/dictionary.txt
  .vscodeignore
Labels: bug

#1597 pre-commit: enable ruff and black
  .config/dictionary.txt
  .pre-commit-config.yaml
  .vscode/extensions.json
  examples/dynamic_inventory.py
  packages/ansible-language-server/test/fixtures/completion/dynamic_inventory.py
  packages/ansible-language-server/tools/version_sync.py
  pyproject.toml
  syntaxes/plist2xml.py
  syntaxes/xml2plist.py
  test/testFixtures/common/collections/ansible_collections/testorg/collection_1/plugins/lookup/lookup_1.py
  tools/helper
  tools/precheck.py
Labels: skip-changelog

#1589 Run CI on forked repos when no tags are fetched
  pyproject.toml
  tools/helper
Labels: skip-changelog

#1595 AAP-32828: Lightspeed: WCA Issue: 124 (Update EC2 example)
  src/features/lightspeed/playbookGeneration.ts
Labels: bug

#1598 Run CI nightly on the main branch
  .github/workflows/ci.yaml
Labels: skip-changelog

#1600 Add workflow dispatch option for publish
  .github/workflows/ci.yaml
Labels: bug

#1601 Address some local development issues
  .config/requirements.in
  .github/workflows/ci.yaml
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#1602 Refactoring walkthrough UI tests to reduce duplication
  test/ui-test/walkthroughUiTest.ts
Labels: bug

#1604 Use python3.12 for testing
  .github/workflows/ci.yaml
Labels: skip-changelog

#1605 Address asdf plugins add issue
  tools/test-setup.sh
Labels: skip-changelog

#1603 Run shellcheck with python3.12
  .pre-commit-config.yaml
Labels: skip-changelog

#1606 Update minimum pre-commit version
  .pre-commit-config.yaml
Labels: skip-changelog

#1607 Remove duplicate dynamic_inventory file in examples
  examples/ansible.cfg
  examples/dynamic_inventory.py
Labels: bug

#1570 lightspeed: move down the default timeout to 28s
  src/definitions/constants.ts
  src/features/lightspeed/api.ts
Labels: bug

#1614 Start using uv instead of pip during testing
  .config/requirements.in
  .pre-commit-config.yaml
  tools/test-setup.sh
Labels: skip-changelog
