Repository ansible/vscode-ansible, pull requests merged in 2024-04, with the labels that each got.

#1182 Enable ALS tests on GHA
  .config/Taskfile_shared.yml
  .envrc
  .gitattributes
  .github/workflows/ack.yml
  .github/workflows/ci.yaml
  .tool-versions
  Taskfile.yml
  packages/ansible-language-server/.github/workflows/task.yml
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/tools/test-setup.sh
  packages/ansible-language-server/tools/vscode.sh
Labels: skip-changelog

#1168 AAP-22175: Make CloudFront check more robust
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/handleApiError.ts
  test/units/lightspeed/contentmatches.test.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: enhancement

#1194 Add publish pipeline
  .config/dictionary.txt
  .github/workflows/ci.yaml
Labels: skip-changelog

#1195 Prepare for 24.4.0 release
  CHANGELOG.md
  package.json
Labels: skip-changelog

#1202 Do not require ack for before check
  .github/workflows/ci.yaml
Labels: skip-changelog

#1203 Make publish work without needing a clone
  tools/publish.sh
Labels: skip-changelog

#1191 Lightspeed: Trigger explanation using the context menu (right click)
  package.json
Labels: enhancement

#1197 Setup asdf in release.yml
  .github/workflows/release.yml
Labels: skip-changelog

#1190 explanation: spinning icon during the loading
  src/features/lightspeed/playbookExplanation.ts
Labels: enhancement

#1205 Remove unused playbook generation setting
  package.json
Labels: skip-changelog

#1208 Change grep option -E to -P to support \d
  tools/release.sh
Labels: skip-changelog

#1206 Build and dependency updates
  .config/dictionary.txt
  .depcheckrc.yml
  .pre-commit-config.yaml
  Taskfile.yml
  package.json
  packages/ansible-language-server/package.json
  tools/package.sh
  yarn.lock
Labels: skip-changelog

#1209 Update language-server dependency to 9.x
  package.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1210 Add safeguard for @types/vscode version
  .depcheckrc.yml
  .github/dependabot.yml
  Taskfile.yml
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1188 Update Playbook Generation and added UI tests
  .vscodeignore
  cspell.config.yaml
  media/playbookGeneration/style.css
  package.json
  packages/ansible-language-server/src/ansibleLanguageService.ts
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/contentCreator/welcomePage.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/playbookGeneration/playbookGenerationPage.ts
  src/features/playbookGeneration/welcomePage.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  src/webview/apps/playbookGeneration/main.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/generations.ts
  test/mockLightspeedServer/server.ts
  test/mockLightspeedServer/summaries.ts
  test/testFixtures/lightspeed/playbook_4.yml
  test/ui-test/lightspeedUiTest.ts
  tools/run-ui-test-with-mock-lightspeed-server.sh
  webpack.config.ts
Labels: enhancement

#1223 Upgrade to eslint v9
  .depcheckrc.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  eslint.config.mjs
  package.json
  packages/ansible-language-server/package.json
  packages/ansible-language-server/src/services/ansibleLint.ts
  packages/ansible-language-server/src/services/ansiblePlaybook.ts
  packages/ansible-language-server/src/utils/misc.ts
  packages/ansible-language-server/test/providers/validationProvider.test.ts
  packages/ansible-language-server/tools/settings-doc-generator.ts
  packages/ansible-language-server/tsconfig.json
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/feedbackWebviewViewProvider.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/utils/feedbackView.ts
  src/features/lightspeed/utils/promiseHandlers.ts
  src/features/pythonMetadata.ts
  src/features/utils/ansibleCfg.ts
  src/features/utils/lightspeed.ts
  src/features/vault.ts
  src/treeView.ts
  src/utils/telemetryUtils.ts
  test/mockLightspeedServer/contentmatches.ts
  test/testScripts/diagnostics/testAnsibleWithoutEE.test.ts
  test/testScripts/diagnostics/testYamlWithoutEE.test.ts
  test/units/lightspeed/contentmatches.test.ts
  tsconfig.json
  yarn.lock
Labels: skip-changelog

#1228 Add documentation
  .config/Taskfile_shared.yml
  .config/requirements.in
  .github/workflows/ci.yaml
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  Taskfile.yml
  docs/README.md
  docs/als/README.md
  docs/als/changelog.md
  docs/als/development.md
  docs/als/settings.md
  docs/contributing.md
  docs/development.md
  docs/faq/integrate-ansible-lint-with-language-server-venv.md
  docs/images/ansible-lint.gif
  docs/images/favicon.ico
  docs/images/go-to-definition.gif
  docs/images/hover-documentation-module.png
  docs/images/jinja-expression.gif
  docs/images/logo.png
  docs/images/logo.svg
  docs/images/smart-completions.gif
  docs/images/syntax-highlighting.png
  docs/images/yaml-validation.gif
  docs/usage-data.md
  mkdocs.yml
  packages/ansible-language-server/.config/requirements.in
  packages/ansible-language-server/.prettierignore
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/docs/changelog-fragments.d/350.feature.md
  packages/ansible-language-server/mkdocs.yml
  packages/ansible-language-server/package.json
  packages/ansible-language-server/tools/settings-doc-generator.ts
Labels: skip-changelog

#1222 Add spinning icon during API calls for playbook generation
  .gitignore
  media/playbookGeneration/style.css
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
Labels: minor

#1229 Avoid update of chai to v5
  .github/dependabot.yml
Labels: skip-changelog

#1231 eslint: address forbidden non-null assertion
  eslint.config.mjs
  src/features/ansibleTox/controller.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/pythonMetadata.ts
  test/helper.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1215 Install collection in editable mode
  .vscodeignore
  examples/README.md
  media/contentCreator/scaffoldCollectionPageStyle.css
  media/contentCreator/welcomePageStyle.css
  package.json
  src/extension.ts
  src/features/contentCreator/scaffoldCollectionPage.ts
  src/features/contentCreator/types.ts
  src/features/contentCreator/welcomePage.ts
  src/features/playbookGeneration/welcomePage.ts
  src/webview/apps/contentCreator/scaffoldCollectionPageApp.ts
  src/webview/apps/contentCreator/welcomePageApp.ts
  webpack.config.ts
Labels: bug, feature

#1234 Rewrite language server npm release pipeline
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  .gitignore
  docs/README.md
  docs/als/README.md
  docs/als/changelog.md
  docs/als/development.md
  docs/als/settings.md
  docs/contributing.md
  docs/development.md
  mkdocs.yml
  package.json
  packages/ansible-language-server/.github/CODEOWNERS
  packages/ansible-language-server/.github/ISSUE_TEMPLATE/bug_report.yml
  packages/ansible-language-server/.github/ISSUE_TEMPLATE/config.yml
  packages/ansible-language-server/.github/ISSUE_TEMPLATE/feature_request.yml
  packages/ansible-language-server/.github/dependabot.yml
  packages/ansible-language-server/.github/release-drafter.yml
  packages/ansible-language-server/.github/workflows/ack.yml
  packages/ansible-language-server/.github/workflows/prepare-release.yml
  packages/ansible-language-server/.github/workflows/publish.yml
  packages/ansible-language-server/.github/workflows/push.yml
  packages/ansible-language-server/README.md
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/changelog.md
  packages/ansible-language-server/package.json
  packages/ansible-language-server/tools/can-release.sh
  packages/ansible-language-server/tools/release.sh
  packages/ansible-language-server/tools/settings-doc-generator.ts
  tools/test-setup.sh
  yarn.lock
Labels: skip-changelog

#1236 LightspeedExplorer view as a Webview and new button
  .vscodeignore
  package.json
  src/extension.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/utils/explorerView.ts
  src/webview/apps/lightspeed/explorer/main.ts
  test/ui-test/lightspeedUiTest.ts
  webpack.config.ts
Labels: enhancement

#1240 build: avoid taskfile deps due to its parallel nature
  .config/Taskfile_shared.yml
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#1241 Automatically dedupe dependabot updates
  .github/workflows/dedupe.yml
Labels: skip-changelog

#1238 eslint: no-unsafe-member-access (partial)
  docs/usage-data.md
  eslint.config.mjs
  src/features/ansibleTox/controller.ts
  src/features/contentCreator/scaffoldCollectionPage.ts
  src/features/contentCreator/types.ts
  src/features/utils/python.ts
  src/features/vault.ts
  src/utils/telemetryUtils.ts
  src/webview/apps/contentCreator/scaffoldCollectionPageApp.ts
Labels: skip-changelog

#1244 lightspeedExplorer: minor UI adjustments
  .vscodeignore
  media/lightspeedExplorerView/style.css
  package.json
  src/features/lightspeed/utils/explorerView.ts
Labels: skip-changelog

#1248 built improvements
  .config/Taskfile_shared.yml
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#1247 lightspeed/login: reduce the size of the text
  media/lightspeedExplorerView/style.css
  src/features/lightspeed/utils/explorerView.ts
Labels: skip-changelog

#1246 Playbook Generation UI error cases
  src/extension.ts
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1167 Allow use of ${workspaceFolder} in python.interpreterPath
  docs/README.md
  packages/ansible-language-server/src/utils/commandRunner.ts
  packages/ansible-language-server/test/utils/runCommand.test.ts
Labels: bug

#1252 Redirect express logs to separate log file
  package.json
Labels: skip-changelog

#1250 More build logic fixes
  .config/Taskfile_shared.yml
  .config/dictionary.txt
  Taskfile.yml
  package.json
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/feedback.ts
  test/mockLightspeedServer/generations.ts
  test/mockLightspeedServer/server.ts
  test/mockLightspeedServer/summaries.ts
  tools/test-setup.sh
  yarn.lock
Labels: skip-changelog

#1253 Ensure dbus is running under Linux
  .config/Taskfile_shared.yml
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: skip-changelog

#1256 Reduce console logging during testing
  packages/ansible-language-server/test/providers/hoverProvider.test.ts
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
  src/features/lightspeed/contentMatchesWebview.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: skip-changelog

#1260 More types
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/providers/completionProviderUtils.ts
  packages/ansible-language-server/src/providers/semanticTokenProvider.ts
  packages/ansible-language-server/src/services/ansibleInventory.ts
  packages/ansible-language-server/src/services/ansibleLint.ts
  packages/ansible-language-server/src/services/docsLibrary.ts
  packages/ansible-language-server/src/services/docsLibraryUtilsForPAC.ts
  packages/ansible-language-server/src/services/metadataLibrary.ts
  packages/ansible-language-server/src/utils/commandRunner.ts
  packages/ansible-language-server/src/utils/pathUtils.ts
  packages/ansible-language-server/src/utils/webUtils.ts
  packages/ansible-language-server/tsconfig.json
  src/features/lightspeed/utils/webUtils.ts
Labels: skip-changelog

#1262 Add type to smartFilter
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/providers/completionProvider.test.ts
Labels: skip-changelog

#1257 TextArea on Playbook Generation page should expand automatically
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
Labels: minor

#1267 More types
  packages/ansible-language-server/src/interfaces/extensionSettings.ts
  packages/ansible-language-server/src/services/ansibleLint.ts
  packages/ansible-language-server/src/services/docsLibrary.ts
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/services/settingsManager.ts
  packages/ansible-language-server/test/providers/settingsManager.test.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
Labels: skip-changelog

#1268 More types
  packages/ansible-language-server/src/services/ansibleConfig.ts
  packages/ansible-language-server/src/utils/getAnsibleMetaData.ts
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
Labels: skip-changelog

#1270 More types
  packages/ansible-language-server/src/interfaces/extensionSettings.ts
  packages/ansible-language-server/src/services/ansiblePlaybook.ts
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/services/settingsManager.ts
  packages/ansible-language-server/test/consoleOutput.ts
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/providers/definitionProvider.test.ts
  packages/ansible-language-server/test/providers/hoverProvider.test.ts
  packages/ansible-language-server/test/utils/runCommand.test.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  packages/ansible-language-server/tools/settings-doc-generator.ts
  packages/ansible-language-server/tsconfig.json
Labels: skip-changelog

#1272 More types
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/src/providers/completionProvider.ts
  packages/ansible-language-server/src/providers/validationProvider.ts
  packages/ansible-language-server/src/services/ansibleInventory.ts
  packages/ansible-language-server/test/providers/hoverProvider.test.ts
  packages/ansible-language-server/test/providers/validationProvider.test.ts
Labels: skip-changelog

#1259 support RHSSO authentication for Lightspeed
  .config/dictionary.txt
  package.json
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/feedbackView.ts
  src/features/lightspeed/utils/webUtils.ts
  src/interfaces/lightspeed.ts
  src/treeView.ts
  src/utils/logger.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  test/testScripts/lightspeed/testLightspeedUser.test.ts
  test/units/lightspeed/contentmatches.test.ts
Labels: enhancement

#1278 Enable strict mode in language server tsconfig file
  packages/ansible-language-server/src/providers/completionProvider.ts
  packages/ansible-language-server/src/utils/yaml.ts
  packages/ansible-language-server/test/rootMochaHooks.ts
  packages/ansible-language-server/tsconfig.json
Labels: skip-changelog

#1273 Show connect on expiry
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/statusBar.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  test/testScripts/lightspeed/testLightspeedUser.test.ts
Labels: minor

#1254 Remove Lightspeed content feedback
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
  src/interfaces/lightspeed.ts
Labels: skip-changelog

#1279 Consolidate tsconfig.json file
  packages/ansible-language-server/src/utils/yaml.ts
  packages/ansible-language-server/tsconfig.json
  tsconfig.base.json
  tsconfig.json
Labels: skip-changelog

#1219 Fix setting IDs in README.md
  docs/README.md
Labels: bug

#1280 Ensure packages als is functional
  .npmrc
  packages/ansible-language-server/changelog.md
  packages/ansible-language-server/out/test-als/package.json
  packages/ansible-language-server/package.json
  packages/ansible-language-server/test/validate-ls.ts
  packages/ansible-language-server/tools/can-release.sh
Labels: skip-changelog

#1277 Adjust ALS .js.map files for debugging
  Taskfile.yml
  package.json
  webpack.config.ts
Labels: skip-changelog

#1276 Make thumbUp/Down icons 'sticky' at bottom on explanation panel
  media/playbookGeneration/style.css
  src/features/lightspeed/playbookExplanation.ts
Labels: skip-changelog

#1255 lightspeedExplorerView: hide role is undefined
  src/features/lightspeed/utils/explorerView.ts
Labels: skip-changelog

#1283 Revert "Adjust ALS .js.map files for debugging"
  Taskfile.yml
  package.json
  webpack.config.ts
Labels: skip-changelog
