Repository ansible/vscode-ansible, pull requests merged in 2024-08, with the labels that each got.

#1476 test: update selenium webdriver
  package.json
  yarn.lock
Labels: skip-changelog

#1444 test: use python3 executable everywhere
  examples/collections/ansible_collections/my_namespace/my_collection/plugins/modules/my_test.py
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
  packages/ansible-language-server/test/utils/runCommand.test.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  test/units/contentCreator/utilities.test.ts
  tools/test-setup.sh
Labels: skip-changelog, qa

#1484 Reduce test console noise
  package.json
Labels: skip-changelog

#1486 test: enforce use of our own virtualenv
  .config/Taskfile_shared.yml
  Taskfile.yml
Labels: skip-changelog

#1488 test: avoid false positive project coverage failures due to rounding errors
  codecov.yml
Labels: skip-changelog

#1362 lightspeed: remove an unused block
  src/features/lightspeed/inlineSuggestions.ts
Labels: minor

#1490 Additional logging when proxy block requests to lightspeed
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
Labels: minor

#1500 AAP-28376: lightspeed: move playbook exp/gen away from the LSP server
  packages/ansible-language-server/package-lock.json
  packages/ansible-language-server/package.json
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/interfaces/lightspeedApi.ts
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/handleApiError.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/errors.ts
  src/features/lightspeed/utils/oneClickTrial.ts
  src/interfaces/lightspeed.ts
  test/units/lightspeed/contentmatches.test.ts
  test/units/lightspeed/utils/handleApiError.test.ts
  yarn.lock
Labels: enhancement

#1495 AAP-26820: Task not found in ARI postprocess results
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/utils/data.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1503 Unmount volumes when execution environment is disabled
  packages/ansible-language-server/test/helper.ts
  test/helper.ts
Labels: bug

#1504 Update collection path for some als tests
  packages/ansible-language-server/test/providers/completionProvider.test.ts
  packages/ansible-language-server/test/providers/completionResolver.test.ts
  packages/ansible-language-server/test/providers/definitionProvider.test.ts
  packages/ansible-language-server/test/providers/hoverProvider.test.ts
  packages/ansible-language-server/test/providers/validationProvider.test.ts
Labels: bug

#1508 Delete ALS EE cache before and after E2E and ALS tests
  .config/dictionary.txt
  packages/ansible-language-server/test/helper.ts
  packages/ansible-language-server/test/rootMochaHooks.ts
  test/helper.ts
  test/testScripts/e2eTestSuiteLauncher.test.ts
Labels: bug

#1509 Require ALS tests
  .github/workflows/ci.yaml
Labels: skip-changelog

#1512 Move Lightspeed One Click Trial out of experimental features
  src/features/lightspeed/api.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/oneClickTrial.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
Labels: skip-changelog

#1514 Upload artifacts from matrix "test (linux)"
  .github/workflows/ci.yaml
Labels: skip-changelog

#1415 Adopt community-ansible-dev-tools image
  .config/Containerfile
  .config/requirements.in
  .devcontainer/devcontainer.json
  docs/als/settings.md
  package.json
  packages/ansible-language-server/.config/Dockerfile
  packages/ansible-language-server/.config/requirements.in
  packages/ansible-language-server/package.json
  packages/ansible-language-server/src/services/settingsManager.ts
  packages/ansible-language-server/test/index.ts
  src/settings.ts
  test/testFixtures/hover/with_ee/1.yml
  test/testFixtures/settings.json
  tools/test-setup.sh
Labels: enhancement, qa

#1519 WCA: Handle 'HTTP404: Failed to get remaining capacity' response
  src/features/lightspeed/errors.ts
  test/units/lightspeed/utils/handleApiError.test.ts
Labels: enhancement
