Repository ansible/vscode-ansible, pull requests merged in 2024-06, with the labels that each got.

#1337 playbookExplanation: improve the wording
  src/features/lightspeed/playbookExplanation.ts
Labels: minor

#1339 Playbook Generation syntax highlighting and editable ordered list
  .config/dictionary.txt
  media/playbookGeneration/style.css
  package.json
  src/features/lightspeed/playbookGeneration.ts
  src/features/utils/syntaxHighlighter.ts
  src/webview/apps/common/editableList.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
  test/units/lightspeed/editableList.test.ts
  webpack.config.ts
  yarn.lock
Labels: enhancement

#1344 Playbook Generation wizardId support
  packages/ansible-language-server/src/ansibleLanguageService.ts
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/generations.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1309 Update msg for WCA model not found error and create a new error no org linked
  src/features/lightspeed/errors.ts
  test/units/lightspeed/handleApiError.test.ts
Labels: minor

#1341 lightspeed: rename SentimentEvent to SentimentFeedbackEvent
  src/interfaces/lightspeed.ts
Labels: skip-changelog

#1347 Playbook Explanation Thumbs button visibility issue
  media/playbookGeneration/style.css
Labels: skip-changelog

#1349 Switch prettier to maintained fork
  .pre-commit-config.yaml
  docs/als/README.md
Labels: skip-changelog

#1346 Code coverage support in UI test
  .c8rc
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .nycrc.yml
  .vscodeignore
  Taskfile.yml
  package.json
  src/features/lightspeed/playbookGeneration.ts
  test/index.ts
  test/ui-test/extensionUITest.ts
  test/ui-test/lightspeedUiTest.ts
  tools/coverage-all.sh
  tools/run-ui-test-with-mock-lightspeed-server.sh
  webpack.config.ts
  yarn.lock
Labels: skip-changelog

#1348 Enable sending only ansibleMetadata event
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/utils/data.ts
  src/utils/telemetryUtils.ts
Labels: bug

#1345 Capture user operations on Playbook Generation UI
  src/definitions/lightspeed.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/feedback.ts
  test/mockLightspeedServer/server.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1333 lightspeed/telemetry: trigger even when explanation is opened
  src/extension.ts
  src/features/lightspeed/playbookExplanation.ts
  src/interfaces/lightspeed.ts
Labels: skip-changelog

#1352 Fix "not under rootDir" issue in webpack
  test/ui-test/lightspeedUiTest.ts
  webpack.config.ts
Labels: bug

#1330 Improve auto-assignment of `ansible` language to files
  package.json
Labels: bug

#1357 Modify Ansible content creator welcome page
  media/playbookGeneration/playbookGeneration.css
  package.json
  src/extension.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/playbookGeneration/welcomePage.ts
  src/webview/apps/contentCreator/welcomePageApp.ts
Labels: enhancement

#1360 Hide Lightspeed menu from Content Creator welcome page for now
  src/features/playbookGeneration/welcomePage.ts
Labels: skip-changelog

#1359 Always enable the remove content suggestion header
  docs/README.md
  package.json
  src/features/lightspeed/inlineSuggestions.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
Labels: minor

#1361 Prepare for 24.6 release
  package.json
Labels: skip-changelog

#1365 Upload als test code coverage data
  .github/workflows/ci.yaml
  packages/ansible-language-server/package.json
  tools/convert-als-coverage-lcov.sh
Labels: skip-changelog

#1364 Support content match for playbooks w/o tasks
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/utils/parsePlays.ts
  test/units/lightspeed/parsePlays.test.ts
Labels: skip-changelog

#1370 Last lines on Playbook Explanation are hard to read
  media/playbookGeneration/style.css
  src/features/lightspeed/playbookExplanation.ts
Labels: skip-changelog

#1371 Lightspeed Explorer CSS adjustments
  media/lightspeedExplorerView/style.css
  src/features/lightspeed/utils/explorerView.ts
Labels: skip-changelog

#1367 Playbook Generation UI editable list edge cases
  src/webview/apps/common/editableList.ts
  test/units/lightspeed/editableList.test.ts
Labels: skip-changelog

#1372 Add CLOSE_ACCEPT/CLOSE_CANCEL to generation actions
  src/definitions/lightspeed.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1369 Added initial README for Tests.
  test/README.md
Labels: enhancement

#1375 Update the segment sources
  package.json
Labels: skip-changelog

#1366 Gracefully handle playbook generation and explanation not available
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/errors.ts
  packages/ansible-language-server/src/interfaces/lightspeedApi.ts
  packages/ansible-language-server/src/utils/handleApiError.ts
  packages/ansible-language-server/test/utils/handleApiError.test.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/utils/errors.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/explanations.ts
  test/mockLightspeedServer/generations.ts
  test/testFixtures/lightspeed/playbook_explanation_feature_unavailable.yml
  test/ui-test/lightspeedUiTest.ts
  test/units/lightspeed/contentmatches.test.ts
Labels: enhancement

#1379 Playbook explanation for task files and playbooks w/o tasks
  src/extension.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/playbookExplanation.ts
  test/testFixtures/lightspeed/playbook_5.yml
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/ui-test/lightspeedUiTest.ts
Labels: minor

#1384 Playbook Generation link shown w/ a smaller font
  src/features/playbookGeneration/welcomePage.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1388 Tami takamiya/content creator visibility issue with light color theme
  media/playbookGeneration/playbookGeneration.css
  src/features/playbookGeneration/welcomePage.ts
  src/webview/apps/contentCreator/welcomePageApp.ts
Labels: skip-changelog

#1391 Change release drafter to use MAJOR.MINOR.PATCH
  .github/release-drafter.yml
Labels: skip-changelog

#1387 Refactor versioning of extension
  .github/workflows/ci.yaml
  .tool-versions
  Taskfile.yml
  package.json
  tools/get-marketplace-version.sh
  tools/helper
  tools/package.sh
  tools/publish.sh
Labels: skip-changelog

#1380 Include variable values with enhanced context sent from VSCode
  src/features/lightspeed/utils/readVarFiles.ts
  test/units/lightspeed/utils/updateRolesContext.ts
Labels: enhancement

#1392 Prevent dependabot from updating @types/vscode
  .github/dependabot.yml
Labels: skip-changelog

#1318 Add unit tests for content creator utility functions
  package.json
  test/units/contentCreator/utilities.test.ts
Labels: skip-changelog

#1376 Fix creator folder opening
  package.json
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
Labels: bug

#1389 Outline should not be updated if it is given in the input to generation API
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/generations.ts
  test/ui-test/lightspeedUiTest.ts
Labels: bug

#1390 Enable explanation button immediately when a playbook is generated
  src/features/lightspeed/playbookGeneration.ts
Labels: bug

#1399 Add fetch-depth 0 to checkout action
  .github/workflows/ci.yaml
Labels: skip-changelog

#1401 tools/helper: ensure version_info is defined
  tools/helper
Labels: skip-changelog

#1381 Action field in Recommendation events have a blank/null value
  src/features/lightspeed/api.ts
  src/features/lightspeed/inlineSuggestions.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: bug

#1406 Remove --readme-path flag from ovsx
  tools/helper
Labels: bug

#1403 Feedback webview UI test
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1405 Lightspeed Authentication UI Tests (Linux only)
  test/mockLightspeedServer/openUrl.ts
  test/mockLightspeedServer/server.ts
  test/ui-test/allTestsSuite.ts
  test/ui-test/lightspeedAuthUiTest.ts
  test/ui-test/uiTestHelper.ts
  tools/run-ui-test-with-mock-lightspeed-server.sh
Labels: skip-changelog
