Repository ansible/vscode-ansible, pull requests merged in 2024-05, with the labels that each got.

#1285 Standardise the functionalities across all the ansible-creator functionalities in the extension
  .vscodeignore
  media/baseStyles/baseFormStyle.css
  media/contentCreator/createAnsibleCollectionPageStyle.css
  media/contentCreator/createAnsibleProjectPageStyle.css
  package.json
  src/extension.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/welcomePage.ts
  src/features/playbookGeneration/welcomePage.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  webpack.config.ts
Labels: enhancement

#1230 Support wait window setting for Lightspeed inline suggestion
  docs/README.md
  package.json
  src/extension.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  test/helper.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
Labels: enhancement

#1290 Prepare for 24.5 release
  package.json
Labels: skip-changelog

#1284 eslint: address more exceptions
  eslint.config.mjs
  packages/ansible-language-server/src/providers/completionProviderUtils.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/errors.ts
  src/features/utils/ansible.ts
  test/units/lightspeed/contentmatches.test.ts
Labels: skip-changelog

#1293 Specify --readme-path to vsce
  tools/publish.sh
Labels: skip-changelog

#1292 eslint address unbound-method exception
  eslint.config.mjs
  src/features/ansibleTox/controller.ts
Labels: skip-changelog

#1291 eslint: address more exceptions
  eslint.config.mjs
  packages/ansible-language-server/src/services/executionEnvironment.ts
  packages/ansible-language-server/src/utils/docsFinder.ts
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/contentCreator/welcomePageApp.ts
Labels: skip-changelog

#1296 Feature to open collection in new window, with a new virtual environment
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
Labels: bug

#1297 Add "Getting Started" walkthrough
  .vscodeignore
  media/walkthroughs/gettingStarted/all-adt-tools.png
  media/walkthroughs/gettingStarted/ansible-env/environment-statusbar.png
  media/walkthroughs/gettingStarted/ansible-env/no-ansible-env copy.png
  media/walkthroughs/gettingStarted/ansible-env/no-ansible-env.png
  media/walkthroughs/gettingStarted/ansible-env/no-ansible-lint-env copy.png
  media/walkthroughs/gettingStarted/ansible-env/no-ansible-lint-env.png
  media/walkthroughs/gettingStarted/ansible-env/ok-env copy.png
  media/walkthroughs/gettingStarted/ansible-env/ok-env.png
  media/walkthroughs/gettingStarted/ansible-extension-settings.png
  media/walkthroughs/gettingStarted/ansible-features/ansible-lint-crop.gif
  media/walkthroughs/gettingStarted/ansible-features/go-to-definition-crop.gif
  media/walkthroughs/gettingStarted/ansible-features/hover-documentation-module-crop.png
  media/walkthroughs/gettingStarted/ansible-features/smart-completions-crop.gif
  media/walkthroughs/gettingStarted/ansible-features/syntax-highlighting-crop.png
  media/walkthroughs/gettingStarted/ansibleEnvironment.md
  media/walkthroughs/gettingStarted/language-selector.png
  media/walkthroughs/gettingStarted/language-statusbar.png
  media/walkthroughs/gettingStarted/languageFeatures.md
  media/walkthroughs/gettingStarted/learn-more.png
  media/walkthroughs/gettingStarted/open-folder.png
  media/walkthroughs/gettingStarted/run-ansible-playbook.png
  media/walkthroughs/gettingStarted/selectAnsibleLanguage.md
  package.json
  src/extension.ts
Labels: enhancement

#1305 Playbook Generation UI update
  media/playbookGeneration/style.css
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
Labels: minor

#1301 Telemetry for Playbook Summary API (ThumbsUp/Down)
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/interfaces/lightspeedApi.ts
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
Labels: enhancement

#1308 lightspeed: adjust the playbook gen prompt form placeholder
  src/features/lightspeed/playbookGeneration.ts
Labels: skip-changelog

#1307 lightspeed: use interface to wrap explanation answer
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/interfaces/lightspeedApi.ts
  src/features/lightspeed/playbookExplanation.ts
Labels: skip-changelog

#1313 lightspeed/explanation: send the feedback events
  packages/ansible-language-server/src/ansibleLanguageService.ts
  src/extension.ts
  src/features/lightspeed/playbookExplanation.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookExplanation/main.ts
Labels: skip-changelog

#1322 Refactor codecov upload logic
  .github/workflows/ci.yaml
Labels: skip-changelog

#1324 gha: use a single dependabot update for both folders
  .github/dependabot.yml
Labels: skip-changelog

#1323 gha: avoid duplicate warnings about already published versions
  .config/Taskfile_shared.yml
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#1325 Adjust wait time in Lightspeed test with mock server
  test/helper.ts
  test/mockLightspeedServer/server.ts
  test/testScripts/lightspeed/e2eInlineSuggestion.test.ts
Labels: skip-changelog

#1316 Playbook Generation ThumbsUp/Down UI fix
  src/extension.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/ui-test/lightspeedUiTest.ts
Labels: skip-changelog

#1326 Make the 'upgrade status' key in ansible-lint metadata consistent
  packages/ansible-language-server/src/utils/getAnsibleMetaData.ts
Labels: bug

#1311 test-setup.sh: check for dbus-broker or dbus-daemon
  tools/test-setup.sh
Labels: skip-changelog

#1320 Merge summaries API into generations API for WCA support
  packages/ansible-language-server/src/ansibleLanguageService.ts
  packages/ansible-language-server/src/interfaces/lightspeedApi.ts
  src/features/lightspeed/playbookGeneration.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/generations.ts
  test/mockLightspeedServer/server.ts
  test/mockLightspeedServer/summaries.ts
  test/ui-test/lightspeedUiTest.ts
Labels: minor

#1329 Add 3rd page to Playbook Generation UI
  media/playbookGeneration/style.css
  packages/ansible-language-server/src/ansibleLanguageService.ts
  src/extension.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  test/mockLightspeedServer/feedback.ts
  test/ui-test/lightspeedUiTest.ts
Labels: minor

#1336 Enable Lightspeed inline suggestion in untitled editor tabs
  src/extension.ts
Labels: enhancement

#1328 Playbook Generation content match support
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/playbookGeneration.ts
  src/interfaces/lightspeed.ts
  test/units/lightspeed/contentmatches.test.ts
Labels: minor
