Repository ansible/vscode-ansible, pull requests merged in 2025-01, with the labels that each got.

#1748 Make build environment more flexible
  .env
  .envrc
  .github/workflows/ci.yaml
  .tool-versions
  .vscode/settings.json
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
  tools/precheck.py
  tools/test-setup.sh
Labels: skip-changelog

#1746 Fix vscode CI failures: ansible-navigator command not found and remove the toast notification pop up
  .github/workflows/ci.yaml
  src/features/contentCreator/addPluginPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: skip-changelog

#1752 Sort quick links view on Ansible Development Tools welcome page
  src/features/quickLinks/quickLinksView.ts
Labels: minor

#1753 Update plugin webview: change the order of plugin type and plugin name in the view
  src/features/contentCreator/addPluginPage.ts
Labels: minor

#1757 tools/helper: accept minor == '0' in release version
  tools/helper
Labels: minor

#1756 Prevent Feedback Panel from Opening on Status Bar Click
  src/features/lightspeed/statusBar.ts
Labels: minor

#1763 Add mkdocs.configuration key to .readthedocs.yml
  .readthedocs.yml
Labels: bug

#1758 [Webview] Replace Collection Project webview to use `@vscode-elements` package
  media/contentCreator/createAnsibleCollectionPageStyle.css
  package.json
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  yarn.lock
Labels: enhancement

#1765 AAP-38438: roleGen: show a message if no collection found
  src/features/lightspeed/roleGeneration.ts
  src/features/lightspeed/roleGeneration/collectionSelectorElement.ts
  src/webview/apps/lightspeed/roleGeneration/main.ts
Labels: minor

#1762 AAP-29950: Swap axios for electron fetch
  .config/dictionary.txt
  .depcheckrc.yml
  .sonarcloud.properties
  package.json
  src/features/lightspeed/api.ts
  src/features/lightspeed/errors.ts
  src/features/lightspeed/handleApiError.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/utils/errors.ts
  test/helper.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedRoleGenTest.ts
  test/ui-test/lightspeedUiTestExplorerTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/units/lightspeed/utils/handleApiError.test.ts
  webpack.config.ts
  yarn.lock
Labels: enhancement

#1776 package.json: ensure we give enough memory to Webpack
  package.json
Labels: bug

#1779 lightspeed: clean up, we never send playbookGenerationFeedback event
  src/extension.ts
  src/interfaces/lightspeed.ts
Labels: minor

#1780 roleGen: code clean up
  media/roleGeneration/style.css
  src/features/lightspeed/roleGeneration.ts
  src/webview/apps/lightspeed/roleGeneration/main.ts
Labels: minor

#1782 roleGen: show collection in final file path
  src/features/lightspeed/roleGeneration.ts
  test/ui-test/lightspeedRoleGenTest.ts
Labels: minor

#1784 lightspeedRoleGenTest: fix the tests
  test/ui-test/lightspeedRoleGenTest.ts
Labels: bug

#1783 Update collection project webview to show divider and Logs label
  media/contentCreator/createAnsibleCollectionPageStyle.css
  src/features/contentCreator/createAnsibleCollectionPage.ts
Labels: bug

#1791 Upload all coverage reports to codecov
  .github/workflows/ci.yaml
  tools/test-launcher.sh
Labels: bug

#1794 Update Clear All buttons to work with vscode-elements limitations
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
Labels: bug

#1773 Update Playbook Project webview to use `@vscode-elements` package
  .sonarcloud.properties
  media/contentCreator/createAnsibleProjectPageStyle.css
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1778 Right click option for building an EE when execution-environment.yml is recognized
  package.json
  src/extension.ts
  src/features/utils/buildExecutionEnvironment.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement
