Repository ansible/vscode-ansible, pull requests merged in 2025-07, with the labels that each got.

#2099 Change media codec to H.264 and remove unused files
  media/walkthroughs/compress.sh
  media/walkthroughs/create-ansible-creator.mp4
  media/walkthroughs/create-lightspeed-completion.mp4
  media/walkthroughs/create-lightspeed-playbook.mp4
  media/walkthroughs/discoverAdt/adt-create.md.html
  media/walkthroughs/discoverAdt/adt-test.md.html
  media/walkthroughs/startAutomatingPlaybook/enable-lightspeed.md.html
  media/walkthroughs/test-ansible-lint.mp4
  media/walkthroughs/test-molecule.mp4
  media/walkthroughs/test-tox-ansible.mp4
  media/walkthroughs/unusedResources/all-adt-tools.png
  media/walkthroughs/unusedResources/ansible-env/environment-statusbar.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-env copy.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-env.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-lint-env copy.png
  media/walkthroughs/unusedResources/ansible-env/no-ansible-lint-env.png
  media/walkthroughs/unusedResources/ansible-env/ok-env copy.png
  media/walkthroughs/unusedResources/ansible-env/ok-env.png
  media/walkthroughs/unusedResources/ansible-extension-settings.png
  media/walkthroughs/unusedResources/ansible-features/ansible-lint-crop.gif
  media/walkthroughs/unusedResources/ansible-features/go-to-definition-crop.gif
  media/walkthroughs/unusedResources/ansible-features/hover-documentation-module-crop.png
  media/walkthroughs/unusedResources/ansible-features/smart-completions-crop.gif
  media/walkthroughs/unusedResources/ansible-features/syntax-highlighting-crop.png
  media/walkthroughs/unusedResources/ansibleEnvironment.md.html
  media/walkthroughs/unusedResources/language-selector.png
  media/walkthroughs/unusedResources/languageFeatures.md.html
  media/walkthroughs/unusedResources/learn-more.png
  media/walkthroughs/unusedResources/run-ansible-playbook.png
  media/walkthroughs/vscode-ansible-intro-compressed.mp4
  media/walkthroughs/vscode-ansible-intro.mp4
  tools/helper
Labels: bug

#2105 Change github.ref_name to github.run_id for download-artifact
  .github/workflows/ci.yaml
Labels: skip-changelog

#2107 Ensure that ui tests are producing junit results
  .github/workflows/ci.yaml
  .mocharc.js
  .vscode-test.mjs
  packages/ansible-language-server/.mocharc.yml
  test/ui/.mocharc.js
  tools/test-launcher.sh
Labels: chore

#2101 Add UI check for minimum required ansible-creator version
  media/contentCreator/addPluginPageStyle.css
  media/contentCreator/createAnsibleProjectPageStyle.css
  media/contentCreator/createRolePageStyle.css
  src/features/contentCreator/utils.ts
  src/features/contentCreator/vue/views/addPluginPagePanel.ts
  src/features/contentCreator/vue/views/createAnsibleCollectionPanel.ts
  src/features/contentCreator/vue/views/createAnsibleProjectPanel.ts
  src/features/contentCreator/vue/views/createRolePanel.ts
  src/features/lightspeed/vue/views/ansibleCreatorUtils.ts
  test/ui/contentCreatorUiTest.ts
  webviews/AddPluginPageApp.vue
  webviews/CreateAnsibleCollectionApp.vue
  webviews/CreateAnsibleProjectApp.vue
  webviews/CreateRoleApp.vue
  webviews/RequirementsBanner.vue
Labels: enhancement

#2114 Pull Git LFS files during CI setup
  tools/test-setup.sh
Labels: bug

#2127 Update Ansible patterns webview subheading
  webviews/AddPatternPageApp.vue
Labels: bug

#2126 Remove use of --path argument in ansible-creator commands
  src/features/lightspeed/vue/views/ansibleCreatorUtils.ts
Labels: bug
