Repository ansible/vscode-ansible, pull requests merged in 2025-04, with the labels that each got.

#1918 lightspeed: remove seat management
  src/features/lightspeed/api.ts
  src/features/lightspeed/contentMatchesWebview.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/statusBar.ts
  src/features/lightspeed/utils/webUtils.ts
  src/interfaces/lightspeed.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/testScripts/lightspeed/testLightspeed.test.ts
  test/testScripts/lightspeed/testLightspeedUser.test.ts
  test/units/lightspeed/contentmatches.test.ts
Labels: minor

#1932 test-launcher.sh: keep a copy of the mock-server logs
  tools/test-launcher.sh
Labels: minor

#1937 Constraint python dependencies to ensure reproducible test results
  .config/constraints.txt
  .config/requirements.in
  .github/dependabot.yml
  .github/workflows/ci.yaml
  Taskfile.yml
  cspell.config.yaml
  packages/ansible-language-server/.config/requirements.in
  pyproject.toml
  tools/test-setup.sh
Labels: skip-changelog, dependencies

#1941 Skip "With EE enabled @ee" als test case
  packages/ansible-language-server/test/providers/validationProvider.test.ts
Labels: skip-changelog

#1925 Various UX improvements to playbook and role gen views
  test/units/lightspeed/utils/outlineLineNumbers.test.ts
  tsconfig.json
  webviews/lightspeed/src/PlaybookGenApp.vue
  webviews/lightspeed/src/RoleGenApp.vue
  webviews/lightspeed/src/components/OutlineReview.vue
  webviews/lightspeed/src/utils/index.ts
  webviews/lightspeed/src/utils/outlineLineNumbers.ts
Labels: bug

#1934 Correct vsce calls from build scripts
  Taskfile.yml
  tools/helper
Labels: skip-changelog

#1902 Check for the minimum ansible-creator version required to initialize an EE project
  src/features/contentCreator/createExecutionEnvPage.ts
Labels: skip-changelog

#1929 Addition of role scaffolding webview using ansible-creator command
  .config/dictionary.txt
  .sonarcloud.properties
  .vscodeignore
  codecov.yml
  media/contentCreator/createRolePageStyle.css
  package.json
  src/extension.ts
  src/features/contentCreator/createRolePage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createRolePageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  webpack.config.ts
Labels: enhancement

#1945 Update podman devcontainer template to match ansible-creator
  .config/dictionary.txt
  resources/contentCreator/createDevcontainer/.devcontainer/podman/devcontainer-template.txt
Labels: bug

#1947 build: Make HOSTNAME environment variable optional
  .config/Taskfile_shared.yml
  .config/mise.toml
  .envrc
  Taskfile.yml
  tools/test-setup.sh
Labels: skip-changelog

#1948 build: replace black with ruff reformat
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
Labels: skip-changelog

#1949 build: enable toml-sort-fix
  .config/dictionary.txt
  .config/mise.toml
  .gitleaks.toml
  .pre-commit-config.yaml
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
Labels: skip-changelog

#1950 build: avoid python build scripts
  .config/Taskfile_shared.yml
  Taskfile.yml
  tools/README.md
  tools/get-image-version
  tools/precheck.py
  tools/precheck.sh
Labels: skip-changelog

#1951 build: bump yarn
  .yarn/releases/yarn-4.7.0.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  package.json
Labels: skip-changelog

#1952 build: address deprecation warning from outdated direnv action
  .github/workflows/ci.yaml
  .tool-versions
Labels: skip-changelog

#1931 Combine explanation webviews and convert to vue.js
  media/roleExplanation/style.css
  src/extension.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/roleExplanation.ts
  src/features/lightspeed/utils/explanationUtils.ts
  src/features/lightspeed/vue/views/explanationPanel.ts
  src/features/lightspeed/vue/views/helper.ts
  src/features/lightspeed/vue/views/panelUtils.ts
  src/features/lightspeed/vue/views/playbookGenPanel.ts
  src/features/lightspeed/vue/views/roleGenPanel.ts
  src/webview/apps/lightspeed/playbookExplanation/main.ts
  src/webview/apps/lightspeed/roleExplanation/main.ts
  test/testScripts/lightspeed/testLightSpeedFunctions.test.ts
  test/ui-test/lightspeedUiTestExplorerTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/lightspeedUiTestRoleExpTest.ts
  vite.config.ts
  webpack.config.ts
  webviews/lightspeed/explanation.html
  webviews/lightspeed/src/ExplanationApp.vue
  webviews/lightspeed/src/components/FeedbackBox.vue
  webviews/lightspeed/src/explanation.ts
Labels: skip-changelog

#1953 build: simplify dependency update logic
  .depcheckrc.yml
  .github/workflows/ci.yaml
  Taskfile.yml
  package.json
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/package-lock.json
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1963 build: ensure vsix filename is valid for merge queues
  .github/workflows/ci.yaml
Labels: skip-changelog

#1927 build: switch WSL based testing to self-hosted runner
  .github/workflows/ci.yaml
  test/testRunner.ts
  tools/test-launcher.sh
Labels: skip-changelog

#1962 build: enable webpack caching
  .github/workflows/ci.yaml
  webpack.config.ts
Labels: skip-changelog

#1957 Enable ALS test-result.xml junit reporting to codecov.io
  .depcheckrc.yml
  .github/workflows/ci.yaml
  package.json
  packages/ansible-language-server/.mocharc.yml
  packages/ansible-language-server/package.json
  test/fix-junit-reports.ts
  yarn.lock
Labels: skip-changelog
