Repository ansible/vscode-ansible, pull requests merged in 2025-05, with the labels that each got.

#1966 Replace nyc with c8 for als coverage
  .c8rc
  .github/workflows/ci.yaml
  packages/ansible-language-server/.c8rc
  packages/ansible-language-server/.nycrc.yml
  packages/ansible-language-server/package.json
  yarn.lock
Labels: skip-changelog

#1965 Update environment message to reference the devcontainer webview
  src/features/contentCreator/createDevcontainerPage.ts
  src/webview/apps/quickLinks/quickLinksApp.ts
  src/webview/apps/welcomePage/welcomePageApp.ts
Labels: bug

#1969 Use cobertura xml reporting for ui testing
  .c8rc
  .github/workflows/ci.yaml
  tools/test-launcher.sh
Labels: skip-changelog

#1978 Use cobertura output for unit tests
  .github/workflows/ci.yaml
  .gitignore
  .pre-commit-config.yaml
  .sonarcloud.properties
  package.json
  test/index.ts
  test/ui-test/lightspeedRoleGenTest.ts
  test/unit/.c8rc
  test/unit/contentCreator/utilities.test.ts
  test/unit/lightspeed/contentmatches.test.ts
  test/unit/lightspeed/editableList.test.ts
  test/unit/lightspeed/parsePlays.test.ts
  test/unit/lightspeed/utils/getRoleNameFromRolePath.test.ts
  test/unit/lightspeed/utils/getRoleNamePathFromFilePath.test.ts
  test/unit/lightspeed/utils/handleApiError.test.ts
  test/unit/lightspeed/utils/multiLinePromptForMultiTasks.test.ts
  test/unit/lightspeed/utils/outlineLineNumbers.test.ts
  test/unit/lightspeed/utils/samples/collections/ansible_collections/community/dummy/galaxy.yml
  test/unit/lightspeed/utils/samples/collections/ansible_collections/community/empty/README
  test/unit/lightspeed/utils/samples/collections/ansible_collections/community/general/MANIFEST.json
  test/unit/lightspeed/utils/samples/collections/ansible_collections/empty/README
  test/unit/lightspeed/utils/samples/collections/ansible_collections/openstack/cloud/MANIFEST.json
  test/unit/lightspeed/utils/samples/collections/ansible_collections/virt_lightning/virt_lightning/MANIFEST.json
  test/unit/lightspeed/utils/scanner.test.ts
  test/unit/lightspeed/utils/updateRolesContext.ts
  test/units/lightspeed/utils/samples/collections/ansible_collections/community/broken_MANIFEST/MANIFEST.json
Labels: skip-changelog

#1979 Ensure ui tests reside in test/ui
  .github/workflows/ci.yaml
  .sonarcloud.properties
  test/ui/contentCreatorUiTest.ts
  test/ui/contentCreatorUiTestNoCreatorTest.ts
  test/ui/extensionUITest.ts
  test/ui/lightspeedAuthUiTest.ts
  test/ui/lightspeedOneClickTrialUITest.ts
  test/ui/lightspeedRoleGenTest.ts
  test/ui/lightspeedUiTestActiveBarTest.ts
  test/ui/lightspeedUiTestExplorerTest.ts
  test/ui/lightspeedUiTestPlaybookExpTest.ts
  test/ui/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui/lightspeedUiTestPlaybookGenNotAvailableTest.ts
  test/ui/lightspeedUiTestPlaybookGenTest.ts
  test/ui/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui/lightspeedUiTestRoleExpTest.ts
  test/ui/lightspeedUiTestStatusBarAndExplorerViewNoLSTest.ts
  test/ui/lightspeedUiTestStatusBarAndExplorerViewTest.ts
  test/ui/terminalUiTest.ts
  test/ui/uiTestHelper.ts
  test/ui/walkthroughUiTest.ts
  test/ui/welcomePageUITest.ts
  tools/test-launcher.sh
Labels: skip-changelog

#1975 Avoid potentially unnecessary webpack step inside task-ui
  Taskfile.yml
Labels: skip-changelog

#1982 chore: use npm project directory instead of __dirname
  Taskfile.yml
  test/index.ts
  test/testRunner.ts
Labels: skip-changelog

#1994 test-launcher: call extest run-tests with the -c
  tools/test-launcher.sh
Labels: bug

#1995 Bump vscode-extension-tester to latest
  package.json
  test/ui/contentCreatorUiTest.ts
  test/ui/lightspeedAuthUiTest.ts
  test/ui/lightspeedOneClickTrialUITest.ts
  test/ui/lightspeedUiTestExplorerTest.ts
  test/ui/uiTestHelper.ts
  yarn.lock
Labels: skip-changelog

#1990 chore: refactor e2e tests to use vscode-test cli
  .config/Taskfile_shared.yml
  .config/mise.toml
  .depcheckrc.yml
  .github/workflows/ci.yaml
  .gitignore
  .sonarcloud.properties
  .vscode-test.mjs
  eslint.config.mjs
  package.json
  packages/ansible-language-server/.c8rc
  packages/ansible-language-server/codecov.yml
  pyproject.toml
  test/e2e/rootMochaHooks.ts
  test/index.ts
  test/testRunner.ts
  tools/test-launcher.sh
  tsconfig.base.json
  yarn.lock
Labels: skip-changelog

#2001 chore: disable mkdocs-material social plugin
  mkdocs.yml
Labels: skip-changelog

#1998 chore: renamed test/testScripts to test/e2e
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .nycrc.yml
  .sonarcloud.properties
  .vscode-test.mjs
  test/e2e/diagnostics/testAnsibleWithoutEE.test.ts
  test/e2e/diagnostics/testYamlWithoutEE.test.ts
  test/e2e/e2eTestSuiteLauncher.test.ts
  test/e2e/hover/testWithEE.test.ts
  test/e2e/hover/testWithoutEE.test.ts
  test/e2e/lightspeed/e2eInlineSuggestion.test.ts
  test/e2e/lightspeed/testLightSpeedFunctions.test.ts
  test/e2e/lightspeed/testLightspeed.test.ts
  test/e2e/lightspeed/testLightspeedUser.test.ts
  test/e2e/outsideWorkspace/testExtensionForFilesOutsideWorkspace.test.ts
  test/lib/nyc.d.ts
  test/ui/mockLightspeedServer/completion.ts
  test/ui/mockLightspeedServer/contentmatches.ts
  test/ui/mockLightspeedServer/explanations.ts
  test/ui/mockLightspeedServer/feedback.ts
  test/ui/mockLightspeedServer/me.ts
  test/ui/mockLightspeedServer/meMarkdown.ts
  test/ui/mockLightspeedServer/openUrl.ts
  test/ui/mockLightspeedServer/playbookGeneration.ts
  test/ui/mockLightspeedServer/roleExplanations.ts
  test/ui/mockLightspeedServer/roleGeneration.ts
  test/ui/mockLightspeedServer/server.ts
  tools/test-launcher.sh
Labels: skip-changelog

#2004 chore: simplify taskfile config
  .config/Taskfile_shared.yml
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
Labels: skip-changelog

#2006 Avoid console spam while running e2e tests
  .depcheckrc.yml
  .mocharc.yml
  .vscode-test.mjs
  package.json
  test/e2e/e2eTestSuiteLauncher.test.ts
  test/e2e/rootMochaHooks.ts
  yarn.lock
Labels: skip-changelog

#2012 Addressed multiple issues with development documentation
  .github/pull_request_template.md
  .markdownlint.yaml
  .markdownlintignore
  .pre-commit-config.yaml
  .readthedocs.yml
  Taskfile.yml
  docs/README.md
  docs/development.md
  docs/development/additional_resources.md
  docs/development/debug_extension.md
  docs/development/extension_code_structure.md
  docs/development/index.md
  docs/development/main.md
  docs/development/media/extension-code-structure.png
  docs/development/media/server-code-structure.png
  docs/development/media/webview-communication-flow.png
  docs/development/media/webview-in-extension.png
  docs/development/media/webview-lifecycle.png
  docs/development/project_structure.md
  docs/development/server_code_structure.md
  docs/development/test_code.md
  docs/development/vite.md
  docs/development/webview_guide.md
  mkdocs.yml
Labels: bug

#1986 mockLightspeedServer: flush the logs before exit
  test/ui/mockLightspeedServer/server.ts
Labels: chore

#1852 Remove most sleep() function calls from ui tests
  test/ui/contentCreatorUiTest.ts
  test/ui/contentCreatorUiTestNoCreatorTest.ts
  test/ui/lightspeedOneClickTrialUITest.ts
  test/ui/lightspeedRoleGenTest.ts
  test/ui/lightspeedUiTestActiveBarTest.ts
  test/ui/lightspeedUiTestExplorerTest.ts
  test/ui/lightspeedUiTestPlaybookExpTest.ts
  test/ui/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui/lightspeedUiTestPlaybookGenNotAvailableTest.ts
  test/ui/lightspeedUiTestPlaybookGenTest.ts
  test/ui/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui/lightspeedUiTestRoleExpTest.ts
  test/ui/lightspeedUiTestStatusBarAndExplorerViewTest.ts
  test/ui/terminalUiTest.ts
  test/ui/uiTestHelper.ts
  test/ui/walkthroughUiTest.ts
  test/ui/welcomePageUITest.ts
Labels: skip-changelog

#2003 AAP-43340: Expose the Lightspeed Auth provider to other extensions
  package.json
Labels: enhancement

#2017 Remove duplicated section in README
  docs/README.md
Labels: skip-changelog

#2010 docs: clarify use of vite for development
  docs/development/vite.md
Labels: skip-changelog

#2019 chore: avoid trigger run when PR title/description is edited
  .github/workflows/ci.yaml
Labels: chore

#2015 Update keywords for file inspection to include ansible.builtin.import_playbook FQCN
  docs/README.md
  src/features/fileAssociation.ts
  src/features/utils/applyFileInspectionForKeywords.ts
Labels: enhancement

#2018 Reduce extension archive size in half
  .vscodeignore
  tools/helper
Labels: bug

#2021 Fix bug where role explanation always shows up in context menu
  package.json
  src/extension.ts
  test/ui/lightspeedUiTestPlaybookExpTest.ts
  test/ui/lightspeedUiTestRoleExpTest.ts
Labels: bug

#2022 Attach vsix file to github release
  .github/workflows/ci.yaml
Labels: chore

#2034 gha: do not run ack as part of ci workflow
  .github/workflows/ci.yaml
Labels: chore

#2041 Separate extension overview page from documentation main page
  README.md
Labels: bug

#2044 chore: sort settings.json fixture
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .gitignore
  .pre-commit-config.yaml
  test/testFixtures/settings.json
Labels: chore

#2009 chore: Ensure we run all ui tests and capture their reports
  .config/dictionary.txt
  .depcheckrc.yml
  .github/workflows/ci.yaml
  .mocharc.yml
  Taskfile.yml
  eslint.config.mjs
  package.json
  test/ui/.mocharc.js
  test/ui/lightspeedAuthUiTest.ts
  test/ui/lightspeedOneClickTrialUITest.ts
  test/ui/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui/mockLightspeedServer/server.ts
  test/ui/terminalUiTest.ts
  tools/_utils.sh
  tools/helper
  tools/test-launcher.sh
  tools/test-setup.sh
  yarn.lock
Labels: chore

#2049 chore: avoid console pollution during unit test execution
  .mocharc.js
  .mocharc.yml
  eslint.config.mjs
  test/mochaHooks.ts
  tsconfig.json
Labels: chore

#2051 lightspeed: move our VueJs components in a dedicated directory
  webviews/lightspeed/src/ExplanationApp.vue
  webviews/lightspeed/src/PlaybookGenApp.vue
  webviews/lightspeed/src/RoleGenApp.vue
  webviews/lightspeed/src/components/lightspeed/FeedbackBox.vue
  webviews/lightspeed/src/components/lightspeed/FinalPreviewAsync.vue
  webviews/lightspeed/src/components/lightspeed/GeneratedFileEntry.vue
  webviews/lightspeed/src/components/lightspeed/OutlineReview.vue
  webviews/lightspeed/src/components/lightspeed/PromptExampleBox.vue
  webviews/lightspeed/src/components/lightspeed/PromptField.vue
  webviews/lightspeed/src/components/lightspeed/StatusBoxCollectionName.vue
  webviews/lightspeed/src/components/lightspeed/StatusBoxPrompt.vue
Labels: skip-changelog

#2026 Enabling konflux
  .config/dictionary.txt
  .tekton/vscode-ansible-pull-request.yaml
  .tekton/vscode-ansible-push.yaml
  cspell.config.yaml
  vscode-ansible.Containerfile
Labels: skip-changelog
