Repository ansible/vscode-ansible, pull requests merged in 2025-09, with the labels that each got.

#2158 welcome page Webview migration to vue
  examples/devfile.yaml
  media/welcomePage/style.css
  src/extension.ts
  src/features/welcomePage/index.ts
  src/features/welcomePage/welcomePagePanel.ts
  src/webview/apps/welcomePage/welcomePageApp.ts
  test/ui/welcomePageUITest.ts
  vite.config.ts
  webpack.config.ts
  webviews/WelcomePageApp.vue
  webviews/vite-env.d.ts
  webviews/welcome-page.html
  webviews/welcome-page.ts
Labels: enhancement

#2162 Add patterns schema to jsonValidation list
  package.json
Labels: feat

#2184 fix: use uv.lock to manage python test dependencies
  .config/constraints.txt
  .config/mise.toml
  .config/requirements.in
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  .tool-versions
  Taskfile.yml
  cspell.config.yaml
  eslint.config.mjs
  mkdocs.yml
  pyproject.toml
  tools/_utils.sh
  tools/test-setup.sh
  uv.lock
Labels: fix
