Repository ansible/vscode-ansible, pull requests merged in 2025-06, with the labels that each got.

#2057 Migrating playbook project webview to use Vite JS/Vue
  .sonarcloud.properties
  media/contentCreator/createAnsibleProjectPageStyle.css
  src/extension.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/lightspeed/vue/views/createAnsibleProjectPanel.ts
  src/features/lightspeed/vue/views/helper.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  vite.config.ts
  webpack.config.ts
  webviews/lightspeed/create-ansible-project.html
  webviews/lightspeed/src/CreateAnsibleProject.vue
  webviews/lightspeed/src/create-ansible-project.ts
Labels: enhancement

#2052 doc: extend the dev doc for ViteJs
  .config/dictionary.txt
  .sonarcloud.properties
  docs/development/vite.md
  package.json
  src/extension.ts
  src/features/lightspeed/vue/views/helloWorld.ts
  vite.config.ts
  webviews/lightspeed/hello-world.html
  webviews/lightspeed/src/HelloWorld.vue
  webviews/lightspeed/src/hello-world.ts
Labels: documentation

#2063 Add ADE `--im=cfg` flag for collection webview
  src/definitions/constants.ts
  src/features/contentCreator/utils.ts
  src/features/lightspeed/vue/views/helper.ts
  test/ui/contentCreatorUiTest.ts
  webviews/CreateAnsibleCollectionApp.vue
Labels: bug

#2050 chore: simplify test names
  packages/ansible-language-server/test/providers/completionProvider.test.ts
  packages/ansible-language-server/test/providers/completionResolver.test.ts
  packages/ansible-language-server/test/providers/definitionProvider.test.ts
  packages/ansible-language-server/test/providers/hoverProvider.test.ts
  packages/ansible-language-server/test/providers/validationProvider.test.ts
  packages/ansible-language-server/test/utils/getAnsibleMetaData.test.ts
  test/e2e/e2eTestSuiteLauncher.test.ts
  test/e2e/lightspeed/e2eInlineSuggestion.test.ts
  test/e2e/lightspeed/testLightSpeedFunctions.test.ts
  test/e2e/lightspeed/testLightspeed.test.ts
  test/e2e/lightspeed/testLightspeedUser.test.ts
  test/e2e/outsideWorkspace/testExtensionForFilesOutsideWorkspace.test.ts
Labels: chore

#2062 Adopt coactions/upload-artifact
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: chore

#2070 Fix ansible-language-server URL in main readme file
  README.md
Labels: bug

#2071 Migrate Plugin webview from webpack to vite/vuejs framework
  .sonarcloud.properties
  media/contentCreator/addPluginPageStyle.css
  src/extension.ts
  src/features/contentCreator/addPluginPage.ts
  src/features/contentCreator/vue/views/addPluginPagePanel.ts
  src/features/lightspeed/vue/views/helper.ts
  src/webview/apps/contentCreator/addPluginPageApp.ts
  test/ui/contentCreatorUiTest.ts
  vite.config.ts
  webpack.config.ts
  webviews/AddPluginPageApp.vue
  webviews/add-plugin.html
  webviews/add-plugin.ts
Labels: enhancement

#2073 Ensure build does not happen without git lfs being active
  .github/workflows/ci.yaml
  tools/test-setup.sh
Labels: chore

#2085 Refactor helper file into Modular Components
  .sonarcloud.properties
  src/features/lightspeed/vue/views/ansibleCreatorUtils.ts
  src/features/lightspeed/vue/views/fileOperations.ts
  src/features/lightspeed/vue/views/helper.ts
  src/features/lightspeed/vue/views/lightspeedUtils.ts
  src/features/lightspeed/vue/views/webviewMessageHandlers.ts
  test/ui/contentCreatorUiTest.ts
Labels: enhancement

#2083 Refactor common functions in vue migrated webviews
  src/features/contentCreator/webviewUtils.ts
  webviews/AddPluginPageApp.vue
  webviews/CreateAnsibleCollectionApp.vue
  webviews/CreateAnsibleProjectApp.vue
  webviews/CreateRoleApp.vue
Labels: chore
