Repository ansible/vscode-ansible, pull requests merged in 2025-03, with the labels that each got.

#1854 Removed Redundant Comments for Clarity
  .github/workflows/ci.yaml
  src/features/runner.ts
  test/ui-test/terminalUiTest.ts
  tools/test-setup.sh
Labels: enhancement

#1860 Update devfile and devcontainer webviews to use vscode-elements
  .sonarcloud.properties
  media/contentCreator/createDevcontainerPageStyle.css
  media/contentCreator/createDevfilePageStyle.css
  src/features/contentCreator/createDevcontainerPage.ts
  src/features/contentCreator/createDevfilePage.ts
  src/webview/apps/contentCreator/createDevcontainerPageApp.ts
  src/webview/apps/contentCreator/createDevfilePageApp.ts
  test/ui-test/contentCreatorUiTestNoCreatorTest.ts
Labels: enhancement

#1862 downgrade primevue until issue 7294 is fixed
  package.json
  yarn.lock
Labels: minor

#1863 test-launcher.sh: reset the VSCode settings between tests
  tools/test-launcher.sh
Labels: minor

#1865 lightspeed/roleGen: enable Telemetry
  test/ui-test/lightspeedRoleGenTest.ts
  webviews/lightspeed/src/RoleGenApp.vue
Labels: minor

#1866 Add support for lightspeed role explanation
  .sonarcloud.properties
  media/roleExplanation/style.css
  package.json
  src/definitions/lightspeed.ts
  src/extension.ts
  src/features/lightspeed/api.ts
  src/features/lightspeed/explorerWebviewViewProvider.ts
  src/features/lightspeed/inlineSuggestion/additionalContext.ts
  src/features/lightspeed/roleExplanation.ts
  src/features/lightspeed/utils/data.ts
  src/features/lightspeed/utils/explorerView.ts
  src/features/lightspeed/utils/getRoleNameFromFilePath.ts
  src/features/lightspeed/utils/getRoleNamePathFromFilePath.ts
  src/features/lightspeed/utils/watchers.ts
  src/interfaces/lightspeed.ts
  src/webview/apps/lightspeed/explorer/main.ts
  src/webview/apps/lightspeed/roleExplanation/main.ts
  test/mockLightspeedServer/roleExplanations.ts
  test/mockLightspeedServer/server.ts
  test/testFixtures/lightspeed/roles/example_role/tasks/main.yml
  test/ui-test/lightspeedUiTestRoleExpTest.ts
  test/units/lightspeed/utils/getRoleNameFromRolePath.test.ts
  test/units/lightspeed/utils/getRoleNamePathFromFilePath.test.ts
  webpack.config.ts
  webviews/lightspeed/src/PlaybookGenApp.vue
Labels: enhancement

#1869 examples: fix the collection name
  examples/collections/ansible_collections/my_namespace/my_collection/galaxy.yml
Labels: bug

#1872 README: updated Lightspeed Getting Started link
  docs/README.md
Labels: documentation, minor

#1871 primevue 4.3.1 with a patch for 7294
  .yarn/patches/primevue-npm-4.3.1-8b2b4a2f18.patch
  package.json
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  webviews/lightspeed/src/playbook-generation.ts
  webviews/lightspeed/src/role-generation.ts
  yarn.lock
Labels: bug

#1873 Add support to scaffold generic module plugins in the plugin webview
  src/features/contentCreator/addPluginPage.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1867 Minimal Fixes for Playbook project and Execution-environment webview
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/createExecutionEnvPage.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1877 lightspeed: remove experimental flag for roleExp/Gen
  package.json
  src/features/lightspeed/utils/explorerView.ts
  src/webview/apps/lightspeed/explorer/main.ts
Labels: minor

#1881 Lightspeed/roleGen: miscellaneous minor changes
  src/features/lightspeed/vue/views/helper.ts
  test/ui-test/lightspeedRoleGenTest.ts
  webviews/lightspeed/src/components/CollectionSelector.vue
  webviews/lightspeed/src/components/PromptField.vue
Labels: minor

#1882 bump primevue to 4.3.2
  .yarn/patches/primevue-npm-4.3.1-8b2b4a2f18.patch
  package.json
  yarn.lock
Labels: minor

#1880 AAP-41894: lightspeed/roleGen: Delay the collection check
  test/ui-test/lightspeedRoleGenTest.ts
  webviews/lightspeed/src/RoleGenApp.vue
  webviews/lightspeed/src/components/CollectionSelector.vue
Labels: minor

#1884 lightspeed/gen: adjust the error box style for Dark mode
  webviews/lightspeed/src/components/ErrorBox.vue
  webviews/lightspeed/src/components/ErrorBoxEntry.vue
Labels: minor

#1888 AAP-42164: lightspeedl: roleGen: properly pass the role name key
  src/features/lightspeed/api.ts
  src/features/lightspeed/vue/views/helper.ts
  src/interfaces/lightspeed.ts
  test/mockLightspeedServer/roleGeneration.ts
  test/ui-test/lightspeedRoleGenTest.ts
  webviews/lightspeed/src/RoleGenApp.vue
Labels: bug

#1892 webpack: ensure server.js is properly bundled
  webpack.config.ts
Labels: bug

#1890 Add support to scaffold an execution-environment project in EE webview
  src/features/contentCreator/createExecutionEnvPage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createExecutionEnvPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1901 Ensure VsCode extension references current devspaces container
  src/definitions/constants.ts
  src/features/contentCreator/createDevfilePage.ts
  src/webview/apps/contentCreator/createDevfilePageApp.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
Labels: enhancement

#1883 lightspeed/gen: enable contentMatch
  src/features/lightspeed/vue/views/helper.ts
Labels: minor

#1905 document the LIGHTSPEED_PREFER_RHSSO_AUTH envvar
  docs/README.md
Labels: minor

#1899 lightspeed: login popup now exposes a "Disable Lightspeed" option
  src/features/lightspeed/lightspeedUser.ts
  src/settings.ts
Labels: enhancement

#1900 changed dir from sample_module to modules
  src/features/contentCreator/addPluginPage.ts
  src/features/quickLinks/quickLinksView.ts
Labels: bug

#1909 lightspeed: avoid a race condition when enabling lightpseed
  src/extension.ts
  src/utils/settings.ts
Labels: bug

#1917 Lightspeed logger clean up
  src/features/lightspeed/base.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
  src/utils/logger.ts
Labels: minor

#1919 lightspeed: use the logger and reduce the severity of msgs
  src/features/lightspeed/api.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/lightSpeedOAuthProvider.ts
  src/features/lightspeed/lightspeedUser.ts
Labels: minor
