Repository ansible/vscode-ansible, pull requests merged in 2025-02, with the labels that each got.

#1766 Add support to scaffold `action` plugins in the plugin webview
  src/features/contentCreator/addPluginPage.ts
  src/features/contentCreator/createDevcontainerPage.ts
  src/features/contentCreator/createSampleExecutionEnvPage.ts
  src/features/quickLinks/quickLinksView.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1790 Update addPlugin webview to use @vscode-elements/elements package
  media/contentCreator/addPluginPageStyle.css
  src/features/contentCreator/addPluginPage.ts
  src/webview/apps/contentCreator/addPluginPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1796 Add new form options with builder capabilities to Execution Environment webview
  .config/dictionary.txt
  .sonarcloud.properties
  .vscodeignore
  codecov.yml
  media/contentCreator/createExecutionEnvPageStyle.css
  media/contentCreator/createSampleExecutionEnvPageStyle.css
  package.json
  src/extension.ts
  src/features/contentCreator/createExecutionEnvPage.ts
  src/features/contentCreator/createSampleExecutionEnvPage.ts
  src/features/contentCreator/types.ts
  src/features/quickLinks/quickLinksView.ts
  src/webview/apps/contentCreator/createExecutionEnvPageApp.ts
  src/webview/apps/contentCreator/createSampleExecutionEnvPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
  test/ui-test/contentCreatorUiTestNoCreatorTest.ts
  webpack.config.ts
Labels: enhancement

#1807 Check for minimum creator version required to scaffold plugins
  src/features/contentCreator/addPluginPage.ts
Labels: bug

#1810 Refactor vscode-elements textfield value workaround
  package.json
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/webview/apps/contentCreator/addPluginPageApp.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
  src/webview/apps/contentCreator/createExecutionEnvPageApp.ts
  src/webview/apps/quickLinks/quickLinksApp.ts
  yarn.lock
Labels: bug

#1812 Update pre-commit dependencies
  .pre-commit-config.yaml
  syntaxes/plist2xml.py
  syntaxes/xml2plist.py
Labels: skip-changelog, dependencies

#1811 Clean up recently reported sonarcloud issues
  media/roleGeneration/style.css
  media/welcomePage/style.css
  packages/ansible-language-server/test/helper.ts
  src/features/contentCreator/addPluginPage.ts
  src/features/contentCreator/createAnsibleCollectionPage.ts
  src/features/contentCreator/createAnsibleProjectPage.ts
  src/features/contentCreator/createDevcontainerPage.ts
  src/features/contentCreator/createDevfilePage.ts
  src/features/contentCreator/createExecutionEnvPage.ts
  src/features/lightspeed/playbookExplanation.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/webview/apps/quickLinks/quickLinksApp.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/uiTestHelper.ts
Labels: bug

#1820 Swap workbench command to close editor with closeAllEditors from the EditorView
  test/ui-test/lightspeedUiTestPlaybookExpTestNoExpTest.ts
Labels: skip-changelog

#1823 Use default sh instead of bash
  .gitignore
  packages/ansible-language-server/src/utils/misc.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  src/features/ansibleTox/runner.ts
  src/features/utils/commandRunner.ts
Labels: bug

#1815 Fix for Collection Plugin and Collection & Playbook Project Webviews
  src/webview/apps/contentCreator/addPluginPageApp.ts
  src/webview/apps/contentCreator/createAnsibleCollectionPageApp.ts
  src/webview/apps/contentCreator/createAnsibleProjectPageApp.ts
Labels: bug

#1824 Fix lightspeed status bar test
  test/ui-test/lightspeedUiTestStatusBarAndExplorerViewTest.ts
Labels: skip-changelog

#1826 Bump mocha timeout to 40s as some tests occasionally run longer than 30
  .mocharc.yml
Labels: skip-changelog

#1833 Use . instead of source for sourcing scripts
  Taskfile.yml
  packages/ansible-language-server/Taskfile.yml
  packages/ansible-language-server/src/utils/misc.ts
  packages/ansible-language-server/test/utils/runCommand.test.ts
  packages/ansible-language-server/test/utils/withInterpreter.test.ts
  src/features/ansibleTox/runner.ts
  src/features/utils/commandRunner.ts
Labels: bug

#1835 Disable flaky lightspeed ui tests
  .mocharc.yml
  test/ui-test/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestStatusBarAndExplorerViewTest.ts
Labels: skip-changelog

#1818 AAP-39941: Migrate the role generation away from webpack
  .c8rc
  .config/dictionary.txt
  .sonarcloud.properties
  .vscode/launch.json
  .vscode/tasks.json
  .vscodeignore
  codecov.yml
  eslint.config.mjs
  media/roleGeneration/style.css
  package.json
  src/env.d.ts
  src/extension.ts
  src/features/env.d.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/roleGeneration.ts
  src/features/lightspeed/roleGeneration/collectionSelectorElement.ts
  src/features/lightspeed/vue/views/helper.ts
  src/features/lightspeed/vue/views/roleGenPanel.ts
  src/features/utils/syntaxHighlighter.ts
  src/webview/apps/lightspeed/playbookGeneration/main.ts
  src/webview/apps/lightspeed/roleGeneration/main.ts
  test/ui-test/lightspeedRoleGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  tools/helper
  tsconfig.json
  vite.config.ts
  webpack.config.ts
  webviews/lightspeed/role-generation/index.html
  webviews/lightspeed/role-generation/src/App.vue
  webviews/lightspeed/role-generation/src/components/CollectionSelectorAsync.vue
  webviews/lightspeed/role-generation/src/components/ErrorBox.vue
  webviews/lightspeed/role-generation/src/components/ErrorBoxEntry.vue
  webviews/lightspeed/role-generation/src/components/FinalPreviewAsync.vue
  webviews/lightspeed/role-generation/src/components/GeneratedFileEntry.vue
  webviews/lightspeed/role-generation/src/components/OutlineReview.vue
  webviews/lightspeed/role-generation/src/components/PromptExampleBox.vue
  webviews/lightspeed/role-generation/src/components/SavedFiles.vue
  webviews/lightspeed/role-generation/src/components/SavedFilesEntry.vue
  webviews/lightspeed/role-generation/src/components/StatusBox.vue
  webviews/lightspeed/role-generation/src/main.ts
  webviews/lightspeed/role-generation/src/utils/index.ts
  webviews/lightspeed/role-generation/src/utils/vscode.ts
  webviews/lightspeed/role-generation/src/vite-env.d.ts
  yarn.lock
Labels: enhancement

#1804 Update plugin webview: Sort and capitalise pluginType dropdown entries
  src/features/contentCreator/addPluginPage.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: enhancement

#1797 Remove Lightspeed Enabled setting
  docs/README.md
  package.json
  src/extension.ts
  src/features/ansibleMetaData.ts
  src/features/lightspeed/base.ts
  src/features/lightspeed/inlineSuggestions.ts
  src/features/lightspeed/lightspeedUser.ts
  src/features/lightspeed/playbookGeneration.ts
  src/features/lightspeed/statusBar.ts
  src/interfaces/extensionSettings.ts
  src/settings.ts
  test/helper.ts
  test/testFixtures/settings.json
  test/ui-test/lightspeedAuthUiTest.ts
  test/ui-test/lightspeedOneClickTrialUITest.ts
  test/ui-test/lightspeedRoleGenTest.ts
  test/ui-test/lightspeedUiTestActiveBarTest.ts
  test/ui-test/lightspeedUiTestExplorerTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoExpTest.ts
  test/ui-test/lightspeedUiTestPlaybookExpTestNoLSTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenNotAvailableTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenTest.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart1Test.ts
  test/ui-test/lightspeedUiTestPlaybookGenWebviewPart2Test.ts
  test/ui-test/lightspeedUiTestStatusBarAndExplorerViewTest.ts
  test/ui-test/uiTestHelper.ts
  test/ui-test/walkthroughUiTest.ts
  tools/test-launcher.sh
Labels: enhancement

#1843 Correct devcontainer webview description
  src/features/contentCreator/createDevcontainerPage.ts
  src/features/quickLinks/quickLinksView.ts
Labels: bug

#1844 Correct image name for environment walkthrough in .vscodeignore
  .vscodeignore
Labels: bug

#1803 Lightspeed: update ligtspeed api paths version to v1
  src/definitions/lightspeed.ts
  test/mockLightspeedServer/server.ts
Labels: enhancement

#1847 roleGen: properly reset the outline when they are changed manually
  webviews/lightspeed/role-generation/src/App.vue
  webviews/lightspeed/role-generation/src/components/OutlineReview.vue
Labels: bug

#1840 AAP-40492: implement the prompt history for the role generation
  src/features/lightspeed/vue/views/helper.ts
  src/features/lightspeed/vue/views/roleGenPanel.ts
  test/ui-test/lightspeedRoleGenTest.ts
  webviews/lightspeed/role-generation/src/App.vue
  webviews/lightspeed/role-generation/src/components/CollectionSelector.vue
  webviews/lightspeed/role-generation/src/components/CollectionSelectorAsync.vue
  webviews/lightspeed/role-generation/src/components/PromptField.vue
Labels: feature, enhancement

#1846 roleGen: Harmonizing Color Schemes and dark-mode support
  webviews/lightspeed/role-generation/src/main.ts
Labels: enhancement

#1848 roleGen: report backend errors in the interface
  src/features/lightspeed/vue/views/helper.ts
Labels: minor

#1849 AAP-40492: make some room for the playbook generation page
  src/features/lightspeed/vue/views/helper.ts
  src/features/lightspeed/vue/views/roleGenPanel.ts
  vite.config.ts
  webviews/lightspeed/role-generation.html
  webviews/lightspeed/src/App.vue
  webviews/lightspeed/src/components/CollectionSelector.vue
  webviews/lightspeed/src/components/ErrorBox.vue
  webviews/lightspeed/src/components/ErrorBoxEntry.vue
  webviews/lightspeed/src/components/FinalPreviewAsync.vue
  webviews/lightspeed/src/components/GeneratedFileEntry.vue
  webviews/lightspeed/src/components/OutlineReview.vue
  webviews/lightspeed/src/components/PromptExampleBox.vue
  webviews/lightspeed/src/components/PromptField.vue
  webviews/lightspeed/src/components/SavedFiles.vue
  webviews/lightspeed/src/components/SavedFilesEntry.vue
  webviews/lightspeed/src/components/StatusBox.vue
  webviews/lightspeed/src/role-generation.ts
  webviews/lightspeed/src/utils/index.ts
  webviews/lightspeed/src/utils/vscode.ts
  webviews/lightspeed/src/vite-env.d.ts
Labels: skip-changelog

#1813 Test for Bug Fixes for Collection/Playbook project webview and Collection Plugin webview
  src/webview/apps/contentCreator/addPluginPageApp.ts
  test/ui-test/contentCreatorUiTest.ts
Labels: bug

#1480 test: switch from ubuntu-22.04 to 24.04
  .config/dictionary.txt
  .github/workflows/ci.yaml
  .readthedocs.yml
  src/features/runner.ts
  test/ui-test/terminalUiTest.ts
  tools/test-setup.sh
Labels: skip-changelog, important
